### ISSUE TITLE
More precise enable / disable of autoclose

### ISSUE THREAD

**Issue by W4RH4WK** [atom/bracket-matcher#241] opened 2016-08-21 15:19 UTC
I recently discovered that bracket-matcher is the plugin causing the autoclosing functionality. It is pretty handy in generally but I am not able to tell it *exactly* which brackets to close automatically, in my case I am fine with `( )`, `[ ]`, `{ }` and `" "` but since I am currently using Atom mainly for rust, I don't want it to auto close `' '`. Only disabling autoclose for single quotes is not possible in the options menu.

Apart from this, the desired setting for automatically closing a bracket depends on the current language, as far as I can say all settings for the bracket-matcher are global. Hence more precise settings are needed.

**Comment by 50Wliu** [comment] 2016-09-25 03:13
This is a duplicate of #121 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-09-25 03:13 UTC
