### ISSUE TITLE
bracket selection with multiple cursors 

### ISSUE THREAD

**Issue by acarl005** [atom/bracket-matcher#231] opened 2016-05-06 08:05 UTC
It would be nice if cmd+ctrl+m would select multiple things when triggered when there are multiple cursors.

**Comment by SandSnip3r** [comment] 2016-05-17 16:57
Right, each cursor should expand to it's given scope. If multiple cursors share a scope, they become a single selection.

**Comment by tnrich** [comment] 2016-09-08 20:05
Please please please someone fix this one!

**Comment by 50Wliu** [comment] 2016-09-25 03:25
This is a duplicate of #192 - feel free to subscribe there for updates.

@tnrich Feel free to send a PR fixing this issue.

**Closed by 50Wliu** 2016-09-25 03:25 UTC
Labels: enhancement
