### ISSUE TITLE
Feature request: Icons on gutter

### ISSUE THREAD

**Issue by vdun** [atom/bracket-matcher#356] opened 2018-08-08 11:47 UTC

**Comment by rsese** [comment] 2018-08-08 17:19
Thanks for the suggestion!  Based on the issue title, I'm going to close as a duplicate of https://github.com/atom/bracket-matcher/issues/97.  For future issues, if you could please use the issue template as much as possible and share more details about your suggestion, that would be helpful for us.

**Closed by rsese** 2018-08-08 17:19 UTC
