### ISSUE TITLE
ctrl - alt + . Cant match the html open close tags

### ISSUE THREAD

**Issue by AMKARTHIK** [atom/bracket-matcher#190] opened 2015-11-22 01:44 UTC
For Example 
If we have a code like below

<html>
<div>
    <span />
    <span />

And after i wish to close the remaining tags with ctrl - alt + .

it will close like below

<html>
<div>
    <span />
    <span />
</spa

n>
</span>
</div>
</html>
[Git Error.txt](https://github.com/atom/bracket-matcher/files/40965/Git.Error.txt)

**Comment by lee-dohm** [comment] 2015-11-22 05:27
Can you be a little more specific about what it is that's going wrong? Can you record a GIF or include in the text of your post a before and after description?

**Comment by ULTIMATEUPGRADE** [comment] 2015-11-22 16:34
Hi @lee-dohm 
In the below attachment I explained about the problem as comment.
[Git Error.txt](https://github.com/atom/bracket-matcher/files/41088/Git.Error.txt)

**Comment by lee-dohm** [comment] 2015-11-22 17:14
Could you include the text inside your comments? I get nervous when people expect me to download random files on the Internet. I'm sure you can understand :grinning:

If you need help formatting your message to include the information in an understandable way, GitHub offers [help on code formatting](https://help.github.com/articles/markdown-basics/#code-formatting).

**Comment by ULTIMATEUPGRADE** [comment] 2015-11-22 17:41
Sorry 
I can't understand what you saying 
i will paste the code below
```html
<html>
<div>
    <span /> # Here I opened and closed a span tag in one line
    <span /> # Here I opened and closed a span tag in one line
</span>   # Here I wish to close my div tag with the keyboard shortcut (ctrl-alt + .)
</span>	  # but it close the already closed span element and then closes the div tag and html tag.
</div>
</html>

**Comment by ULTIMATEUPGRADE** [comment] 2015-11-24 17:01
Hi @lee-dohm  

Did you addressed the issue

**Comment by 50Wliu** [comment] 2016-09-25 03:25
This is a duplicate of #203 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-09-25 03:25 UTC
Labels: more-information-needed
