### ISSUE TITLE
Self-closing tags are incorrectly matched in XML/HTML

### ISSUE THREAD

**Issue by madakk** [atom/bracket-matcher#268] opened 2016-12-26 23:44 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

A self-closing tag (e.g. `<x />`) is wrongly interperted as the opening tag, if it's followed by a closing tag with the same name.

### Steps to Reproduce

1. Enter the following code in an HTML/XML buffer:
```
<x>
  <x />
</x>
```
2. Put cursor on the third line

**Expected behavior:** The opening `<x>` tag should be highlighted as the matching opening tag.

**Actual behavior:** The self-closing `<x />` tag is highlighted as the matching opening tag.

**Reproduces how often:** 100%

### Versions

Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.12.9
npm  3.10.5
node 4.4.5
python
git
visual studio 2013

Windows 8.1

### Additional Information

None.

**Comment by foisonocean** [comment] 2016-12-28 02:49
Same problem in `jsx`

**Comment by 50Wliu** [comment] 2016-12-31 00:22
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #203. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2016-12-31 00:22 UTC
