### ISSUE TITLE
[Request] "Bracket matcher" for LaTeX $$

### ISSUE THREAD

**Issue by j4ckhaal** [atom/bracket-matcher#250] opened 2016-09-24 10:38 UTC
Would it be possible to have a "bracket matcher" for LaTeX dollar signs ($ and $$)? 

Sorry if this is the wrong place to ask.

**Comment by 50Wliu** [comment] 2016-09-25 03:10
This is a duplicate of #121 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-09-25 03:10 UTC
