### ISSUE TITLE
not ignore bracket in comment

### ISSUE THREAD

**Issue by InnerPeace080** [atom/bracket-matcher#191] opened 2015-11-27 09:04 UTC
when i comment a line have a bracket like this (js file)

foo (){
// foo2(){
}

when i click close bracket, it highlight open bracket in comment .

**Comment by izuzak** [comment] 2015-11-27 14:27
Thanks for the report, @InnerPeace080. This looks like a duplicate of https://github.com/atom/bracket-matcher/issues/78 so I'm going to close this in favor of that issue. :v:

**Closed by izuzak** 2015-11-27 14:27 UTC
