### ISSUE TITLE
Auto-completion adding/removing unnecessary brackets

### ISSUE THREAD

**Issue by tomasbedrich** [atom/bracket-matcher#210] opened 2016-02-01 10:17 UTC
When I have:

    else }

and I type an opening curly bracket after the `else` statement, I end up with this:

    else {}}

The same situation is with quotes and all other types of brackets, which is really annoying. Similar behaviour when deleting brackets:

    foo.then(bar();

After deleting the bracket after bar:

    foo.then(bar;

**Comment by jackocnr** [comment] 2016-05-04 21:21
Yes this is infuriating! Though I doubt it's a bug.

Personally, I would be happy with an option to disable auto-completing brackets (etc) when the cursor is in the middle of a line.

**Comment by adambuczynski** [comment] 2016-05-19 23:56
Another problematic case:

```js
return foo > 1);
```

When you type an opening bracket before `foo` you get:

```js
return ()foo > 1);
```

Seems to me the bracket matcher needs to become a bit smarter and be aware of matching brackets already in place.

@lee-dohm any chance someone could have a look at this bug? It's been open for quite some time, and I'm sure it's causing a lot of unnecessary keystrokes every day :)

**Comment by lee-dohm** [comment] 2016-05-20 18:33
@adambuczynski Right now our dev resources are all tied up on higher priority work and/or parental leave (which, to be honest, is also higher priority work :grinning:). I'll ask the team if anyone has some spare time to take a look. I just can't promise anything.

**Comment by adambuczynski** [comment] 2016-05-20 20:39
I understand. I'll see if I can look into this myself one of these days.

**Comment by tomasbedrich** [comment] 2016-05-21 13:27
@adambuczynski I have tested your case, but I wasn't able to replicate it.

**Comment by adambuczynski** [comment] 2016-05-21 21:15
Hmm, I may have over simplified the example too much. I'll see if I can find the exact code it happened with.

**Comment by adambuczynski** [comment] 2016-05-21 21:29
@tomasbedrich ah there, found it! I knew I wasn't going crazy and that I'd seen it happen somehow :)

```js
return $scope.model.roles.indexOf('admin') > -1);
```

Adding an opening bracket before `$scope` yields:

```js
return ()$scope.model.roles.indexOf('admin') > -1);
```

![ss](https://www.dropbox.com/s/jbdowflsjs9q8w9/brackets.gif?dl=1)

**Comment by tomasbedrich** [comment] 2016-05-21 23:23
@adambuczynski confirmed. It is the dollar sign which confuses the matcher.

Generalized and minimized, it is this case:

    [cursor][:any-non-word-character:]

When you type a pair character in this configuration, the editor *always* inserts its counterpart – it doesn't care about pairing, even if `[:any-non-word-character:]` is the desired pair symbol.

On the other hand, in this configuration:

    [cursor][:any-word-character:]

It always inserts only one character of the pair.

**Comment by adambuczynski** [comment] 2016-09-11 00:02
Here's another use case where the bracket matchers adds an unnecessary bracket

![ss](https://www.dropbox.com/s/x1k9od7w5tserl7/brackets-issue.gif?dl=1)

**Comment by 50Wliu** [comment] 2016-09-25 03:34
This is a duplicate of #143 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-09-25 03:34 UTC
Labels: bug, help-wanted
