### ISSUE TITLE
Brackets being matched in comments and strings

### ISSUE THREAD

**Issue by lee-dohm** [atom/bracket-matcher#78] opened 2014-10-27 06:07 UTC
Related: lee-dohm/emacs-flow#3

Repro case can be found (with permission) at: https://gist.github.com/debtosh/e5b25c7719867ec56382
## Repro Steps
1. Open a new file
2. Paste in the text from the Gist linked above
3. Set the grammar to C++
4. Place the cursor after the brace at the end of line 2

**Expected:** Matches brace on line 33
**Actual:** Does not match
1. Place the cursor after the brace _in the comment_ at the end of line 20

**Expected:** Does not match
**Actual:** Matches brace on line 33

If the braces at the end of the comment lines are deleted, all braces match as they would be expected to.

**Comment by Pugio** [comment] 2015-02-04 23:13
Apologies for the multiple references. Stupid git issues on my part.

**Comment by Li-ReDBox** [comment] 2015-06-11 00:34
Any update of fixing this issue?

**Comment by cynecx** [comment] 2015-09-26 21:13
Any updates on this ?

**Comment by kinduff** [comment] 2016-01-13 02:37
Still happening, looks like #105 is missing some test cases.

**Package Version**: 0.79.0
**Atom Version**: 1.3.3
**OS**: 10.10.5

![lguckfatdp](https://cloud.githubusercontent.com/assets/1270156/12283434/cd6f8586-b96b-11e5-87a1-8d7acdc58456.gif)
Editor language is Javascript.

**Comment by isiahmeadows** [comment] 2016-01-13 07:46
Yeah... I've just gotten to the point of ignoring it, simply because I've
half given up on waiting for a fix.

**Comment by Epitaph64** [comment] 2016-01-27 04:17
I can confirm it happening with the PHP grammar as well.

**Comment by shawninder** [comment] 2016-03-16 10:10
Here is an example in a string in javascript:

<img width="319" alt="screen shot 2016-03-16 at 10 57 20" src="https://cloud.githubusercontent.com/assets/484730/13808618/484843a6-eb67-11e5-98c5-e72ebf9e61f0.png">

**Comment by gruppler** [comment] 2016-04-13 05:15
Here's another:
```
function test (remainder) {
  var end = remainder.indexOf('}');
}
```

**Comment by oliperas** [comment] 2016-05-15 15:27
More than a year ago Pugio claimed he had fixed it [https://github.com/atom/bracket-matcher/pull/105](url)

**Comment by Pugio** [comment] 2016-05-15 19:47
I seem to recall there being more edge cases than I'd at first thought. You're welcome to look at the PR and write some tests.

**Comment by edjroot** [comment] 2016-06-05 02:27
Code folding seems to work well. It has to match braces and other symbols in the same manner, right? Can't we just apply its logic to this package?

**Comment by isiahmeadows** [comment] 2016-06-05 04:33
@edjroot That doesn't just match braces, but indentation and syntax type as well, since it collapses indented method chains (e.g. `foo.bar().baz()`) and comments. So I'm not sure it can work in *quite* the same fashion. Now, skipping certain grammars might work (e.g. strings, comments), but I'm not very knowledgeable with the internals of this plugin.

**Comment by edjroot** [comment] 2016-06-05 04:43
Yes, there are quite a few differences and it would have to be worked on, but I'd say it's already a better behavior than the current one, which often becomes useless as shown above.

I'm not familiar with it as well, but maybe we could use it as a more "solid" starting point. This is a very important feature.

**Comment by Nitin-Prabhakar** [comment] 2016-07-11 13:00
I recently switched from Sublime to Atom, and this bug is playing havoc and creating chaotic env within the editor!

Atom is an editor I would hope and love to hold on to, but the bracket matcher just matches wrong brackets and matches braces in code to braces in comments as has been the case for a while now seeing comments!

When would somebody fix this? long awaited I pick up from the thread

**Comment by sradevski** [comment] 2016-07-13 07:09
I can confirm the same thing happening here, using Javascript. ESLint is complaining also about it, and it is really annoying. I hope you fix this, cause it really causes a lot of inconveniences. Here is another gif just for fun.
![problematomeslint](https://cloud.githubusercontent.com/assets/4820812/16794640/23ab7b98-4914-11e6-8143-19da1290cad4.gif)

**Comment by kikz0rsk** [comment] 2016-07-14 20:19
Still happening at least with javascript. Does it take two years to fix this? Running Atom v1.8.0 with Brackets Matcher v0.82.0.
Please can you fix this? Atom is awesome editor, but this is important feature.
![atom](https://cloud.githubusercontent.com/assets/20465221/16854416/1357de50-4a11-11e6-8b39-f93e0521bb58.PNG)

**Comment by kinduff** [comment] 2016-07-15 20:20
If some maintainer post a good starting point or direction of where should this be fixed, I'll take care of the PR.

**Comment by 50Wliu** [comment] 2016-07-15 21:05
I'm thinking that a good idea of solving this is only matching brackets that have the same scopes.  So a bracket in a `comment.line.double-slash.js` won't match a `punctuation.definition.function.body.end.bracket.curly.js` bracket.

Of course this is only in theory and I don't know how well it would work out if actually implemented.  It also would depend on language packages providing accurate tokenization.

**Comment by isiahmeadows** [comment] 2016-07-20 06:41
@50Wliu You could always filter out whatever scopes interfere with it, or use custom logic if you have to. Even if it's hard-coded, it should work.

**Comment by john-f** [comment] 2016-10-15 02:29
I've created a working fix for this: #253.

Unlike #105, which only focused on commented brackets, this solution resolves all issues with brackets in comments, strings, and regular expressions.

I've also added test cases for all of these situations.

**Comment by lee-dohm** [comment] 2016-10-21 03:16
Thanks @john-f, I've brought it up to the team for review :grinning:

**Closed** 2016-11-02 16:40 UTC
Labels: bug

**Comment by artagnon** [comment] 2017-02-20 14:10
Does the fix involve completely ignoring brackets in strings? I see a recent regression where no brackets in strings are being matched. This is quite problematic, since I have strings like this:

```
    std::string input =
        R"CGEL(
            prototype((var(pointer(matrix(complex(double), :)), v)), (), foo);
            function((), (), main) {
                var(int32, i);
                var(int32, j);
                var(matrix(complex(double), 64), snapshotInFreq);
                var(matrix(complex(double), 64), y_data);
                for (i, 0, 1, 8) {
                    foo(cast[pointer(matrix(complex(double), :))](mref(snapshotInFreq, 0u)));
                    for (j, 0, 1, 63) {
                        =(mref(y_data, @j), mval(@snapshotInFreq, @j));
                    }
                }
            }
        )CGEL";
```

This DSL is being used as the input language to the compiler, and many compilers have copious amounts of code like this.

I understand that matching brackets in strings can be problematic for other reasons, but I think the right fix is to match brackets within strings, within comments, and within program text, not treating the entire program as one blob in which to match brackets. I can suggest special-casing C++11 raw strings (the R"") for the moment.

**Comment by Ben3eeE** [comment] 2017-02-20 14:20
@artagnon Yes. There is an open issue for this https://github.com/atom/bracket-matcher/issues/274

**Comment by isiahmeadows** [comment] 2017-02-20 16:41
I think this means validating that the space between brackets remain
matched in its entirety by only one of the following generic scopes:

- source.comment
- source.string
- source (not comment or string)

-----

Isiah Meadows
me@isiahmeadows.com
