### ISSUE TITLE
TypeError: Cannot call method 'isEmpty' of undefined

### ISSUE THREAD

**Issue by benogle** [atom/bracket-matcher#58] opened 2014-08-05 18:37 UTC
From atom/atom#3180

> After pressing Ctrl-+ I got the following error:

```
TypeError: Cannot call method 'isEmpty' of undefined
at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (/usr/local/google/home/skainswo/Atom/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:160:39)
at /usr/local/google/home/skainswo/Atom/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:63:24
at /usr/local/google/home/skainswo/Atom/resources/app/src/config.js:220:20
at /usr/local/google/home/skainswo/Atom/resources/app/node_modules/emissary/lib/emitter.js:133:30
at Array.forEach (native)
at Config.module.exports.Emitter.emit (/usr/local/google/home/skainswo/Atom/resources/app/node_modules/emissary/lib/emitter.js:132:47)
at Config.module.exports.Config.loadUserConfig (/usr/local/google/home/skainswo/Atom/resources/app/src/config.js:80:21)
at PathWatcher. (/usr/local/google/home/skainswo/Atom/resources/app/src/config.js:93:26)
at HandleWatcher. (/usr/local/google/home/skainswo/Atom/resources/app/node_modules/pathwatcher/lib/main.js:132:26)
at HandleWatcher.EventEmitter.emit (events.js:112:17)
at HandleWatcher.onEvent (/usr/local/google/home/skainswo/Atom/resources/app/node_modules/pathwatcher/lib/main.js:60:23)
at /usr/local/google/home/skainswo/Atom/resources/app/node_modules/pathwatcher/lib/main.js:20:41
/usr/local/google/home/skainswo/Atom/resources/app/src/config.js:85
module.exports.Config.loadUserConfig
```

> Preceded by 2 other errors:

```
Uncaught TypeError: Cannot call method 'isEmpty' of undefined /usr/local/google/home/skainswo/Atom/resources/app/node_modules/bracket-matcher/lib/bracket-matcher…:160
module.exports.BracketMatcherView.updateMatch /usr/local/google/home/skainswo/Atom/resources/app/node_modules/bracket-matcher/lib/bracket-matcher…:160
(anonymous function) /usr/local/google/home/skainswo/Atom/resources/app/node_modules/bracket-matcher/lib/bracket-matcher…:63
(anonymous function) /usr/local/google/home/skainswo/Atom/resources/app/src/config.js:220
(anonymous function) /usr/local/google/home/skainswo/Atom/resources/app/node_modules/emissary/lib/emitter.js:133
module.exports.Emitter.emit /usr/local/google/home/skainswo/Atom/resources/app/node_modules/emissary/lib/emitter.js:132
module.exports.Config.update /usr/local/google/home/skainswo/Atom/resources/app/src/config.js:243
module.exports.Config.set /usr/local/google/home/skainswo/Atom/resources/app/src/config.js:155
module.exports.Workspace.increaseFontSize /usr/local/google/home/skainswo/Atom/resources/app/src/workspace.js:348
_results.push._this.(anonymous function) /usr/local/google/home/skainswo/Atom/resources/app/node_modules/delegato/lib/delegator.js:67
(anonymous function) /usr/local/google/home/skainswo/Atom/resources/app/src/workspace-view.js:234
jQuery.event.dispatch /usr/local/google/home/skainswo/Atom/resources/app/node_modules/space-pen/vendor/jquery.js:4676
elemData.handle /usr/local/google/home/skainswo/Atom/resources/app/node_modules/space-pen/vendor/jquery.js:4360
module.exports.KeymapManager.dispatchCommandEvent /usr/local/google/home/skainswo/Atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:400
module.exports.KeymapManager.handleKeyboardEvent /usr/local/google/home/skainswo/Atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:181
(anonymous function) /usr/local/google/home/skainswo/Atom/resources/app/src/window-event-handler.js:90
jQuery.event.dispatch /usr/local/google/home/skainswo/Atom/resources/app/node_modules/space-pen/vendor/jquery.js:4676
elemData.handle /usr/local/google/home/skainswo/Atom/resources/app/node_modules/space-pen/vendor/jquery.js:4360
```

```
Failed to load user config '/usr/local/google/home/skainswo/.atom/config.cson' Cannot call method 'isEmpty' of undefined /usr/local/google/home/skainswo/Atom/resources/app/src/config.js:84
module.exports.Config.loadUserConfig /usr/local/google/home/skainswo/Atom/resources/app/src/config.js:84
(anonymous function) /usr/local/google/home/skainswo/Atom/resources/app/src/config.js:93
(anonymous function) /usr/local/google/home/skainswo/Atom/resources/app/node_modules/pathwatcher/lib/main.js:132
EventEmitter.emit events.js:112
HandleWatcher.onEvent /usr/local/google/home/skainswo/Atom/resources/app/node_modules/pathwatcher/lib/main.js:60
(anonymous function) /usr/local/google/home/skainswo/Atom/resources/app/node_modules/pathwatcher/lib/main.js:20
```

**Comment by despairblue** [comment] 2015-06-03 13:28
This happens when I split a pane and try to type anytthing into the new pane:
```
TypeError: Cannot read property 'isEmpty' of undefined
  at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (/usr/share/atom/resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher-view.js:109:44)
  at /usr/share/atom/resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher-view.js:40:24
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /usr/share/atom/resources/app.asar/src/text-editor.js:239:32
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at DisplayBuffer.module.exports.DisplayBuffer.emitDidChange (/usr/share/atom/resources/app.asar/src/display-buffer.js:302:20)
  at DisplayBuffer.module.exports.DisplayBuffer.updateScreenLines (/usr/share/atom/resources/app.asar/src/display-buffer.js:1473:19)
  at DisplayBuffer.module.exports.DisplayBuffer.handleTokenizedBufferChange (/usr/share/atom/resources/app.asar/src/display-buffer.js:1439:12)
  at /usr/share/atom/resources/app.asar/src/display-buffer.js:5:61
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TokenizedBuffer.module.exports.TokenizedBuffer.handleBufferChange (/usr/share/atom/resources/app.asar/src/tokenized-buffer.js:388:27)
  at /usr/share/atom/resources/app.asar/src/tokenized-buffer.js:62:24
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyChange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:624:20)
  at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:789:16)
  at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:753:14)
  at TextEditor.module.exports.TextEditor.transact (/usr/share/atom/resources/app.asar/src/text-editor.js:1147:26)
  at /usr/share/atom/resources/app.asar/src/text-editor.js:780:24
  at TextEditor.module.exports.TextEditor.mergeSelections (/usr/share/atom/resources/app.asar/src/text-editor.js:1965:43)
  at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/usr/share/atom/resources/app.asar/src/text-editor.js:1939:35)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/usr/share/atom/resources/app.asar/src/text-editor.js:778:19)
  at TextEditor.module.exports.TextEditor.insertText (/usr/share/atom/resources/app.asar/src/text-editor.js:738:21)
  at TextEditor.object.(anonymous function) [as insertText] (/usr/share/atom/resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
  at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (/usr/share/atom/resources/app.asar/src/text-editor-component.js:440:35)
  at HTMLDivElement.<anonymous> (/usr/share/atom/resources/app.asar/src/text-editor-component.js:3:61)
```

Btw: [this](https://github.com/atom/notifications/issues/70) makes reporting errors kind of hard at the moment.

**Comment by despairblue** [comment] 2015-06-03 13:33
Oh when I catch that the error above (to get a formatted stack trace) I get the following:
```
TypeError: Cannot read property 'getScreenPosition' of undefined
  at TextEditor.module.exports.TextEditor.getCursorScreenPosition (/usr/share/atom/resources/app.asar/src/text-editor.js:1331:40)
  at TextEditor.module.exports.TextEditor.isFoldedAtCursorRow (/usr/share/atom/resources/app.asar/src/text-editor.js:2449:44)
  at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (/usr/share/atom/resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher-view.js:116:23)
  at /usr/share/atom/resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher-view.js:40:24
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /usr/share/atom/resources/app.asar/src/text-editor.js:239:32
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at DisplayBuffer.module.exports.DisplayBuffer.emitDidChange (/usr/share/atom/resources/app.asar/src/display-buffer.js:302:20)
  at DisplayBuffer.module.exports.DisplayBuffer.updateScreenLines (/usr/share/atom/resources/app.asar/src/display-buffer.js:1473:19)
  at DisplayBuffer.module.exports.DisplayBuffer.handleTokenizedBufferChange (/usr/share/atom/resources/app.asar/src/display-buffer.js:1439:12)
  at /usr/share/atom/resources/app.asar/src/display-buffer.js:5:61
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TokenizedBuffer.module.exports.TokenizedBuffer.handleBufferChange (/usr/share/atom/resources/app.asar/src/tokenized-buffer.js:388:27)
  at /usr/share/atom/resources/app.asar/src/tokenized-buffer.js:62:24
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyChange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:624:20)
  at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:789:16)
  at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:753:14)
  at TextEditor.module.exports.TextEditor.transact (/usr/share/atom/resources/app.asar/src/text-editor.js:1147:26)
  at /usr/share/atom/resources/app.asar/src/text-editor.js:780:24
  at TextEditor.module.exports.TextEditor.mergeSelections (/usr/share/atom/resources/app.asar/src/text-editor.js:1970:43)
  at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/usr/share/atom/resources/app.asar/src/text-editor.js:1944:35)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/usr/share/atom/resources/app.asar/src/text-editor.js:778:19)
  at TextEditor.module.exports.TextEditor.insertText (/usr/share/atom/resources/app.asar/src/text-editor.js:738:21)
  at TextEditor.object.(anonymous function) [as insertText] (/usr/share/atom/resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
  at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (/usr/share/atom/resources/app.asar/src/text-editor-component.js:440:35)
  at HTMLDivElement.<anonymous> (/usr/share/atom/resources/app.asar/src/text-editor-component.js:3:61)
```

**Comment by despairblue** [comment] 2015-06-03 13:35
:confused: reloading atom fixed this

**Comment by viddo** [comment] 2015-06-23 16:02
I have had trouble reproducing it consistently, but it seems to happen sometimes (not sure on the exact steps yet) when entering "insert mode" using the [vim-mode](https://github.com/atom/vim-mode) package for example.

Anyway, the exception is thrown at [ib/bracket-matcher-view.coffee#L74](https://github.com/atom/bracket-matcher/blob/beb7bf6cbd1e78a38c9764047e9efdf8c1cc4b59/lib/bracket-matcher-view.coffee#L74), because `@editor.getLastSelection()` returns `undefined`. Looking at the [docs it states that it returns a Selection](https://github.com/atom/atom/blob/v0.201.0/src/text-editor.coffee#L2028) but that does obviously not to be true, should be reported on the atom/atom repo perhaps?

Stack trace:
```
Uncaught TypeError: Cannot read property 'isEmpty' of undefined
/Applications/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher-view.js:108 
Uncaught TypeError: Cannot read property 'isEmpty' of undefined/Applications/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher-view.js:108 
module.exports.BracketMatcherView.updateMatch/Applications/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher-view.js:40 
(anonymous function)/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82
module.exports.Emitter.emit/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:236 
(anonymous function)/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82 
module.exports.Emitter.emit/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:311 
module.exports.DisplayBuffer.emitDidChange/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1562 
module.exports.DisplayBuffer.updateScreenLines/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1525 
module.exports.DisplayBuffer.handleTokenizedBufferChange/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:5 (anonymous function)/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82 
module.exports.Emitter.emit/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:403 
module.exports.TokenizedBuffer.handleBufferChange/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:62 
(anonymous function)/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82 
module.exports.Emitter.emit/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:626 
module.exports.TextBuffer.applyChange/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:777 
module.exports.TextBuffer.revertToCheckpoint/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:743 
module.exports.TextBuffer.transact/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1152 
module.exports.TextEditor.transact/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:785
(anonymous function)/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1990 module.exports.TextEditor.mergeSelections/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1964 
module.exports.TextEditor.mergeIntersectingSelections/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:783 
module.exports.TextEditor.mutateSelectedText/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:743 
module.exports.TextEditor.insertText/Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77 
object.(anonymous function)/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:444 
module.exports.TextEditorComponent.onTextInput/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3 (anonymous function)
```

> Which version of Atom are you using?

v0.211.0

> What OS and version are you running?

MacOSX Yosemite 10.10.3

> Do you have the React editor enabled?

I think that setting got removed right? Anyway, have not disabled at least…

> Can you reproduce the issue after completely exiting Atom and restarting using atom --safe?

As mentioned earlier, have not been able to reproduce it consistently.

**Comment by 50Wliu** [comment] 2016-09-25 03:51
No further reports, closing.

**Closed by 50Wliu** 2016-09-25 03:51 UTC
Labels: bug, uncaught-exception
