### ISSUE TITLE
Bad behaviour with multiple selection

### ISSUE THREAD

**Issue by giorgian** [atom/bracket-matcher#68] opened 2014-09-10 13:25 UTC
Pressing quotes (both single and double) when a multiple selection is active replaces all selections with either the first or the last one.

![](http://g.recordit.co/Kq8mTsjxWn.gif)

**Comment by Pugio** [comment] 2015-02-04 18:36
I can't reproduce this.

**Comment by giorgian** [comment] 2015-02-10 14:37
It still affects me with 0.177.0 (on Mac OS X). Just tried with `--safe`, and it still does it. What can I to do help you reproduce this?

**Comment by lee-dohm** [comment] 2015-02-10 15:41
Some repro steps would be nice. Here's what I did that did not reproduce the issue using Atom v0.178.0-89d5dd3 on Mac OS X 10.10.2:

1. Start Atom
1. Create a new untitled file with <kbd>Cmd+N</kbd>
1. Select all with <kbd>Cmd+A</kbd>
1. Split the selection into lines with <kbd>Shift+Cmd+L</kbd>
1. Press <kbd>“</kbd>

**Expected and Actual:** Resulting text is `"first"\n"second"\n`

**Comment by giorgian** [comment] 2015-02-10 16:43
Mystery solved! 

exactly the steps @lee-dohm said, but: expected is `"first"\n"second"\n` and actual is `"second"\n"second"\n` on Atom v0.177.0 (both with all packages and with `--safe`) on Mac OS X 10.10.2...
Except that I use the "U.S. International PC" keyboard layout, where `"` is obtained by pressing <kbd>"+Space</kbd>. So I guess the problem only manifests itself with keyboard layouts where `"` (and others) are the result of more than one keystroke.

Sorry, it occurred to me only now that it would be relevant, I'm so used to that layout that I didn't even think of it.

**Comment by 50Wliu** [comment] 2016-09-25 03:51
This should be fixed starting with Atom 1.12.0.

**Closed by 50Wliu** 2016-09-25 03:51 UTC
Labels: bug
