### ISSUE TITLE
Add extra spacing on auto-closed `()` and `{}`

### ISSUE THREAD

**Issue by NAlexPear** [atom/bracket-matcher#216] opened 2016-02-24 17:51 UTC
The style guide for a codebase I'm working on requires extra spaces between parens and curly braces. For example:
```javascript
//spaced
var newView = Backbone.View.extend( {
  "template": _.template ( tmpl )
} );

//standard
var newView = Backbone.View.extend({
  "template": _.template (tmpl)
});
```
I'd like to be able to add those spaces automatically on auto-completion, since I know that I'll need it every time. Could this possibly be added or a feature?

**Comment by trueter** [comment] 2016-05-10 20:22
I would very much like to see this, too.

**Comment by 50Wliu** [comment] 2016-09-25 03:55
This is a duplicate of #16 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-09-25 03:55 UTC
Labels: enhancement
