### ISSUE TITLE
JS: incorrect bracket matching

### ISSUE THREAD

**Issue by fruggiero** [atom/bracket-matcher#207] opened 2016-01-24 15:38 UTC
![image](https://cloud.githubusercontent.com/assets/4760358/12537154/5516d552-c2b8-11e5-8d31-6cd7164f6862.png)

Looks like it doesn't ignore brackets inside comments.

Atom version:  1.4.0

**Comment by 50Wliu** [comment] 2016-01-24 20:40
Hi @fruggiero, this is a duplicate of #23 and #78 - please subscribe there for updates.

**Closed by 50Wliu** 2016-01-24 20:40 UTC
