### ISSUE TITLE
Double quotes do not close

### ISSUE THREAD

**Issue by chinmaya1011** [atom/bracket-matcher#330] opened 2017-11-05 13:07 UTC
Double quotes _refuse_ to automatically close when they are preceded by an f in Python 3.6, for f-string formatting.

![GIF of issue](https://user-images.githubusercontent.com/11345058/32415018-43f9d7d2-c258-11e7-8535-c1867763f5d3.gif)

When I try to close the quotes it tries to open another pair.
Matching also does not work.

**Comment by rsese** [comment] 2017-12-06 21:59
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/bracket-matcher/issues/318. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-12-06 21:59 UTC
