### ISSUE TITLE
<script tag not detect close tag

### ISSUE THREAD

**Issue by lee-dohm** [atom/bracket-matcher#193] opened 2015-12-03 16:42 UTC
_From @PTKDev on December 3, 2015 14:50_

Hi!
I select with mouse `<script>` open tag but not appear underline on open/close tag: 
![Screenshot](http://openftp.ptkdev.it/Share/img/script_tag_atom.png)

With `<div>` and other tag underline appear:
![Screenshot](http://openftp.ptkdev.it/Share/img/script_tag_atom_work.png)

_Copied from original issue: atom/atom#9932_

**Comment by ricardograca** [comment] 2015-12-08 15:11
For completeness, if both the opening and closing `<script>` tags are on the same line, the underline does appear correctly on both.

**Comment by dbachko** [comment] 2016-02-04 15:21
Reproducible:
![screen shot 2016-02-04 at 10 18 48 am](https://cloud.githubusercontent.com/assets/9260214/12819360/c08dbd1e-cb28-11e5-8976-1ec5eecf89c0.png)

Correct highlight for cursor at the end of the script tag:
![screen shot 2016-02-04 at 10 09 16 am](https://cloud.githubusercontent.com/assets/9260214/12819246/51d6bc2c-cb28-11e5-890c-f4314b3f49f8.png)

**Comment by PhiLhoSoft** [comment] 2016-10-26 14:24
Related: https://discuss.atom.io/t/html-script-tags/34874
As said there, "_if I put the caret just before or just after `<script>`, or just before `</script>`, it works._" (ie. this adds a bit more cases to @dbachko's reporting).

**Comment by 50Wliu** [comment] 2016-10-26 14:34
This may be due to the fact that script tags aren't handled that well in language-html yet.  I'm working on fixing that.

**Comment by 50Wliu** [comment] 2017-10-30 12:12
![script-highlight](https://user-images.githubusercontent.com/2766036/32170203-fd80470c-bd73-11e7-9ca2-f02dd376a510.png)

**Closed by 50Wliu** 2017-10-30 12:12 UTC
Labels: bug

**Comment by ricardograca** [comment] 2017-10-30 12:53
@50Wliu will this fix be in 1.22.0?

**Comment by 50Wliu** [comment] 2017-10-30 13:26
I think so.
