### ISSUE TITLE
Mistakenly matching a bracket located inside a string

### ISSUE THREAD

**Issue by as-cii** [atom/bracket-matcher#254] opened 2016-10-16 09:38 UTC
![bracket-matcher-regression](https://cloud.githubusercontent.com/assets/482957/19416599/dafd2592-9394-11e6-9e78-5af1d21420c4.gif)

You can reproduce this by pasting the following javascript code and moving the cursor to the closing bracket (or to the second opening bracket):

```js
{
  "{"
}
```

@maxbrunsfeld @kuychaco: could this be a regression?

**Comment by maxbrunsfeld** [comment] 2016-10-16 16:32
Don't think so, as we only changed the logic for *when* to update the match, not how it is computed. I could be wrong though; it's worth trying on old versions.

**Comment by Ben3eeE** [comment] 2016-10-16 18:44
Closing as a duplicate of https://github.com/atom/bracket-matcher/issues/78.

**Closed by Ben3eeE** 2016-10-16 18:44 UTC
