### ISSUE TITLE
Wrong selection in HTML inside elements with class or id

### ISSUE THREAD

**Issue by lifewithjoy** [atom/bracket-matcher#194] opened 2015-12-05 17:01 UTC
Hi!

![atom-bracketmatch-issue](https://cloud.githubusercontent.com/assets/1360242/11609016/a197e19e-9b82-11e5-97e0-73db6bc4dda4.jpg)

I noticed such issue, when I tried to select html code inside div class="lists" selection start from 'class="lists"'. It's not a big problem when you have a short part of the  code but this decrease speed of coding when you try to manipulate with many lines of code.

Regards,
Mike

**Comment by izuzak** [comment] 2015-12-05 17:05
Thanks for the report, @lifewithjoy. I think this is a duplicate of https://github.com/atom/bracket-matcher/issues/117 so I'm going to close this in favor of that issue. Let me know if I misunderstood, though.  :v:

**Closed by izuzak** 2015-12-05 17:05 UTC
