### ISSUE TITLE
Disabling autocomplete smart quotes not working on Mac OS X 10.10.4

### ISSUE THREAD

**Issue by davidthewatson** [atom/bracket-matcher#158] opened 2015-07-20 17:25 UTC
I have atom 1.0.2 installed on Mac OS X 10.10.4 with bracket-matcher 0.76.0. I want to turn off autocomplete on quotes. I checked autocomplete smart quotes and still get single and double quotes autocompleting after restarting atom. Is there something else I need to do?

**Comment by sgentle** [comment] 2015-09-13 01:51
I came here with the same issue - after some research it appears to be mostly an expectation-setting problem. I assumed "smart" in this case meant that the quotes were inserted in a smart way, though the use here is as a synonym for "curly quotes".

[The relevant part of the code](https://github.com/atom/bracket-matcher/blob/beb7bf6cbd1e78a38c9764047e9efdf8c1cc4b59/lib/bracket-matcher.coffee#L5) confirms that "smart quotes" are the pairs `“ ”` `‘ ’` `« »` `‹ ›`, *not* `` ' " ` ``. 

I believe it would simultaneously fix the user-level confusion about what smart quotes are, as well as solve the stated problem that we want to disable (dumb) quotes and bracket autocompletion separately, if there were 3 options: Autocomplete Brackets, Autocomplete Quotes, and Autocomplete Smart Quotes.

I can make a pull request for this if you like.

**Comment by lee-dohm** [comment] 2015-09-14 16:17
Probably adding a description field would be good too.

**Comment by kebno** [comment] 2015-12-03 18:46
I see the same.
OS X 10.11.1
Atom 1.2.4 (fully updated)

**Comment by chriswelchgb** [comment] 2016-07-22 16:55
I had the same issue, and it seems that the settings don't seem to take effect until after restart. Two suggestions:
* document that a restart is required
* agree with sgentle that bracket autocomplete and straight quote autocomplete should be separate checkboxes.

I'm running El Capitan and Atom 1.8

**Comment by 50Wliu** [comment] 2016-09-25 03:30
This is a duplicate of #156 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-09-25 03:30 UTC
Labels: bug
