### ISSUE TITLE
If the <div  attributes are on two lines of code, it breaks the bracket matcher

### ISSUE THREAD

**Issue by JoshuaVSherman** [atom/bracket-matcher#349] opened 2018-04-14 14:07 UTC
If the <div  attributes are on two lines of code, it breaks the bracket matcher

### Steps to Reproduce

1. create a div that spans two lines of code
2. nest other divs inside of this div
3. notice that the end div it matches is incorrect

**Expected behavior:** the div matches the end div properly

**Actual behavior:** the div matched a different end div and left the actual end div not being highlighted

**Reproduces how often:** everytime, and it was for two divs in my code, once I moved the div with attributes to be on a single line, in both cases, it was fixed

### Versions
bracket-matcher 0.88.0
atom version 1.23.1

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment] 2018-04-16 22:38
Thanks for the report!  

> atom version 1.23.1

This is a duplicate of https://github.com/atom/bracket-matcher/issues/333 and I believe fixed in 1.25.

**Closed by rsese** 2018-04-16 22:38 UTC
