### ISSUE TITLE
Don't add second quote when selection contains quote.

### ISSUE THREAD

**Issue by Redsandro** [atom/bracket-matcher#227] opened 2016-04-09 16:33 UTC
When starting with `'`, `"` or `, there appears a second quote after the cursor, which is expected and preferred.

When there's a selection, the second quote appears after the selection, which is also expected.

However, when a certain quote is selected and we type a quote because we want to replace it (e.g. double to single quote), we wrap the selection in quotes too. E.g. `"` -> `'"'`. This is not what we are trying to do. I propose when the selection holds one of the three quote types, typing a quote will replace the selection in stead of wrap the selection.

**Comment by z00m1n** [comment] 2016-07-12 12:39
+1

**Comment by 50Wliu** [comment] 2016-09-25 03:36
This is a duplicate of #138 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-09-25 03:36 UTC
