### ISSUE TITLE
Connection line aka identation guide

### ISSUE THREAD

**Issue by ArkhipovK** [atom/bracket-matcher#259] opened 2016-11-24 21:50 UTC
Is it possible to make brackets connection line? Something similar to picture below. Also i aware about indent-guide-improved package, but guidelines there based on identation, not on syntax.
![default](https://cloud.githubusercontent.com/assets/9945452/20610308/65c0f346-b2b9-11e6-95ad-c32c5c441dbb.png)

**Comment by 50Wliu** [comment] 2016-11-24 23:24
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #179. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2016-11-24 23:24 UTC
