### ISSUE TITLE
Default close-tag keybind clashes with certain keyboard mappings

### ISSUE THREAD

**Issue by LouisTakePILLz** [atom/bracket-matcher#100] opened 2015-01-24 21:05 UTC
Using the "French (Canada) Canadian Multilingual Standard" keyboard set, which maps the `< >` chevrons to `RALT-,` and `RALT-.`, respectively, I am unable to properly write closing chevrons (i.e. `>`).

The mapping on this given keyboard obviously clashes with the default `bracket-matcher:close-tag` keybind (being `ctrl-alt-.`), as pressing the key combination triggers both the auto-completion and the key/character (which gets swallowed by the hook).
In my opinion, a *smart* tag detection mechanism should be implemented in order to determine when a "chevron keystroke" closes a tag (and thus, should trigger auto-completion) and when not to block the keystroke.

There are a few workarounds for the current implementation:

- Remap the tag auto-completion command to another key.
- Append an additional `>` whenever a tag is automatically completed, which is, however, not quite ideal considering that it will only partially fix the issue at hand, as the chevron character will only appear when closing a tag, not when the user intends to type an unpaired chevron.

   It also has another drawback; when closing a partial opening tag (e.g. `<tag`), if closed a few lines below the said tag, the chevron will unsurprisingly appear along with the closing tag, resulting in something looking like this:
  ``` js
  <body>
    <h1>Test</h1>
    Test:
    <div
      Proident quis nulla excepteur tempor officia et labore.
    ></div>
  </body>
  ```

This issue is highly related to #54.

**Comment by 50Wliu** [comment] 2015-01-24 23:05
It looks like this might be a duplicate of atom/atom-keymap#35.

**Comment by 50Wliu** [comment] 2015-11-12 01:40
Closing as a duplicate of atom/atom-keymap#35.

**Closed by 50Wliu** 2015-11-12 01:40 UTC
