### ISSUE TITLE
wrong bracket is selected if the code has commented lines with {

### ISSUE THREAD

**Issue by mksuper1** [atom/bracket-matcher#242] opened 2016-08-24 05:08 UTC
Hi,
I noticed a problem where the wrong bracket is selected if the commented codes has { e.g

{1
 {2
   // {3
  4}
5}

if I am bracket 2, bracket 5 will be selected instead of bracket 4.

thanks

**Comment by 50Wliu** [comment] 2016-08-27 17:24
This is a duplicate of #78 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-08-27 17:24 UTC
