### ISSUE TITLE
Failed to activate the bracket-matcher package

### ISSUE THREAD

**Issue by buzz** [atom/bracket-matcher#281] opened 2017-04-11 08:57 UTC
[Enter steps to reproduce:]

1. ...Come to office.
2. ...Type `atom` into terminal.

**Atom**: 1.15.0 x64
**Electron**: 1.4.15
**OS**: linux 4.10.8-1-ARCH
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package 0.85.5

### Stack Trace

Failed to activate the bracket-matcher package

```
At Cannot find module './selector-cache'

Error: Cannot find module './selector-cache'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/usr/lib/electron/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/usr/lib/atom/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:50:27)
    at /packages/bracket-matcher/lib/tag-finder.coffee:3:17)
    at /packages/bracket-matcher/lib/tag-finder.coffee:1:1)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:109:30)
    at Object.value [as .coffee] (/usr/lib/atom/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:50:27)
    at /packages/bracket-matcher/lib/bracket-matcher-view.coffee:4:13)
    at /packages/bracket-matcher/lib/bracket-matcher-view.coffee:1:1)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:109:30)
    at Object.value [as .coffee] (/usr/lib/atom/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:50:27)
    at /packages/bracket-matcher/lib/main.coffee:2:22)
    at /packages/bracket-matcher/lib/main.coffee:1:1)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:109:30)
    at Object.value [as .coffee] (/usr/lib/atom/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

### Commands

```
     -1:11.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-atom-dark-ui)
```

### Non-Core Packages

```
autoclose-html 0.23.0 
autocomplete-modules 1.6.9 
autocomplete-python 1.8.63 
busy-signal 1.3.0 
color-picker 2.2.5 
editorconfig 2.2.2 
file-icons 2.1.2 
git-blame 0.4.12 
goto-definition 1.3.1 
highlight-selected 0.13.1 
intentions 1.1.2 
linter 2.1.2 
linter-eslint 8.1.5 
linter-jshint 3.0.3 
linter-jsonlint 1.3.0 
linter-pylint 2.0.1 
linter-ui-default 1.2.2 
minimap 4.27.1 
pigments 0.39.1 
project-manager 3.3.4 
python-indent 1.0.2 
python-tools 0.6.9 
react 0.16.2 
refactor 0.11.4 
```

**Comment by Ben3eeE** [comment] 2017-04-11 09:33
Thanks for reaching out!

We've determined that this issue is being caused by the use of an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

----

Also I notice that you are running the latest dev version of `bracket-matcher`. You could try to run `apm uninstall bracket-matcher` and see if that fixes this issue :crossed_fingers: It would work for the same issue on an official distribution :grinning: 

You may want to subscribe to https://bugs.archlinux.org/task/50357 or report this issue to the maintainers of the arch Linux package.

**Comment by timfallmk** [comment] 2017-06-21 16:36
@Ben3eeE This issue also appears in the latest beta version for mac running the upstream plugin:

**Atom**: 1.19.0-beta1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package 0.86.0


### Stack Trace

Failed to activate the bracket-matcher package

```
At Cannot read property 'openScopes' of undefined

TypeError: Cannot read property 'openScopes' of undefined
    at TagFinder.module.exports.TagFinder.scopesForPositionMatchRegex (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/bracket-matcher/lib/tag-finder.js:55:28)
    at TagFinder.module.exports.TagFinder.isCursorOnTag (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/bracket-matcher/lib/tag-finder.js:45:25)
    at TagFinder.module.exports.TagFinder.findMatchingTags (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/bracket-matcher/lib/tag-finder.js:174:22)
    at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:128:41)
    at BracketMatcherView.updateMatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:3:65)
    at new BracketMatcherView (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:92:18)
    at /Applications/Atom Beta.app/Contents/Resources/app/node_modules/bracket-matcher/lib/main.js:16:15
    at Workspace.observeTextEditors (/Applications/Atom Beta.app/Contents/Resources/app/src/workspace.js:717:15)
    at Object.activate (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/bracket-matcher/lib/main.js:12:35)
    at Package.module.exports.Package.activateNow (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (/Applications/Atom Beta.app/Contents/Resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:603:52)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/atom-environment.js:843:36
```

### Commands

```
```

### Non-Core Packages

```
accents-ui 1.3.0 
activate-power-mode 2.1.0 
adventurous-syntax 0.2.0 
aligner 1.2.2 
aligner-javascript 1.1.0 
api-docs 0.0.6 
ariake-dark-syntax 0.1.3 
asciidoc-preview 2.10.2 
atom-html-preview 0.1.22 
atom-text-transformer 0.7.0 
atomatigit 1.5.5 
atomic-chrome 0.3.0 
auto-detect-indentation 1.3.0 
auto-update-packages 1.0.1 
autocomplete 0.47.0 
autocomplete-emojis 2.5.0 
autocomplete-python 1.8.64 
base16-eighties-one-dark 1.0.0 
block-comment 0.4.3 
build 0.68.0 
build-dockerfile 1.0.1 
busy 0.7.0 
busy-signal 1.4.3 
circle-ci 0.10.1 
Clean 0.10.0 
Clean2 0.16.0 
commitment 0.1.3 
environment 1.3.1 
feedback 0.38.0 
flask-snippets 0.3.3 
flatwhite-syntax 0.8.1 
floobits 0.32.10 
gist 1.0.0 
git-control 0.9.0 
git-go 1.0.5 
git-plus 7.9.3 
git-time-machine 1.5.9 
github-atom-light-syntax 0.5.0 
gloom 0.6.4 
glowing-cursor 0.1.2 
go-debug 1.4.3 
go-oracle 0.2.1 
go-plus 5.5.5 
go-signature-statusbar 1.2.0 
intentions 1.1.2 
isotope-light-ui 2.2.7 
isotope-ui 2.8.5 
language-asciidoc 1.10.0 
language-diff 0.7.0 
language-docker 1.1.8 
language-fish-shell 1.0.5 
language-gitignore 0.3.0 
language-hcl 0.4.0 
language-nginx 0.8.0 
language-puppet 0.22.0 
language-restructuredtext 1.1.0 
language-scala 1.1.8 
language-systemd 0.1.1 
language-terraform 0.8.1 
language-unix-shell 0.40.1 
linkify 0.11.0 
linter 2.2.0 
linter-golinter 1.2.2 
linter-puppet 1.0.0 
linter-rst 0.0.3 
linter-scalac 1.4.4 
linter-ui-default 1.6.2 
linter-write-good 0.9.0 
markdown-pdf 1.5.4 
markdown-scroll-sync 2.1.2 
markdown-toc 0.4.2 
merge-conflicts 1.4.5 
minimap 4.28.2 
minimap-git-diff 4.3.1 
monokai 0.24.0 
neon-cursor 1.6.0 
neon-selection 0.3.2 
nucleus-dark-ui 0.12.3 
polaris-syntax 0.1.0 
polymorph-ui 1.8.8 
pretty-json 1.6.3 
rain-syntax 2.0.2 
rain-ui 1.0.1 
rainy-night-syntax 0.3.2 
release-notes 0.53.0 
seti-syntax 1.0.1 
seti-ui 1.8.0 
shadow 0.1.0 
shadow-syntax 0.1.0 
sholight 0.2.0 
sync-settings 0.8.2 
the-closer 0.7.0 
transform 0.4.0 
tree-view-git-branch 0.1.2 
typewriter 0.7.0 
unity-dark-ui 2.0.9 
unity-ui 2.1.11 
Zen 0.18.0 
```

**Comment by Positive07** [comment] 2017-07-01 20:11
I'm having this exact issue on Windows 10 x64 Atom 1.19 beta 2

**Comment by haykam821** [comment] 2017-07-02 03:41
Yep, the beta made my file disappear when reopening Atom Beta from a session on macOS 10.13 High Sierra.

**Comment by mrwedders** [comment] 2017-07-04 07:54
Double yep: macOS El Capitan, 1.19 beta 2, wont activate, hasn't since 1.19 first dropped.

**Comment by LouieK22** [comment] 2017-07-04 15:16
Same bug, Windows 10 x64 with the latest updates. Version 1.19-Beta2

**Comment by angelaraya** [comment] 2017-07-05 21:59
Interestingly enough this only happens on one of the two machines that I use, both running 19 beta 2.

1. Open Atom
2. Be welcomed by the error message

**Atom**: 1.19.0-beta2 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package 0.86.0


### Stack Trace

Failed to activate the bracket-matcher package

```
At Cannot read property 'openScopes' of undefined

TypeError: Cannot read property 'openScopes' of undefined
    at TagFinder.module.exports.TagFinder.scopesForPositionMatchRegex (~/AppData/Local/atom/app-1.19.0-beta2/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:55:28)
    at TagFinder.module.exports.TagFinder.isCursorOnTag (~/AppData/Local/atom/app-1.19.0-beta2/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:45:25)
    at TagFinder.module.exports.TagFinder.findMatchingTags (~/AppData/Local/atom/app-1.19.0-beta2/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:174:22)
    at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (~/AppData/Local/atom/app-1.19.0-beta2/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:128:41)
    at BracketMatcherView.updateMatch (~/AppData/Local/atom/app-1.19.0-beta2/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:3:65)
    at new BracketMatcherView (~/AppData/Local/atom/app-1.19.0-beta2/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:92:18)
    at ~/AppData/Local/atom/app-1.19.0-beta2/resources/app/node_modules/bracket-matcher/lib/main.js:16:15
    at Workspace.observeTextEditors (~/AppData/Local/atom/app-1.19.0-beta2/resources/app/src/workspace.js:717:15)
    at Object.activate (~/AppData/Local/atom/app-1.19.0-beta2/resources/app/node_modules/bracket-matcher/lib/main.js:12:35)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.19.0-beta2/resources/app/src/package.js:253:25)
    at ~/AppData/Local/atom/app-1.19.0-beta2/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.19.0-beta2/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.19.0-beta2/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.19.0-beta2/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.19.0-beta2/resources/app/src/package-manager.js:645:40)
    at ~/AppData/Local/atom/app-1.19.0-beta2/resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.19.0-beta2/resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (~/AppData/Local/atom/app-1.19.0-beta2/resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (~/AppData/Local/atom/app-1.19.0-beta2/resources/app/src/package-manager.js:603:52)
    at ~/AppData/Local/atom/app-1.19.0-beta2/resources/app/src/atom-environment.js:843:36
```

### Commands

```
     -0:23.7.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
busy-signal 1.4.3 
file-icons 2.1.8 
intentions 1.1.2 
jumpy 3.1.3 
language-vue 0.23.0 
linter 2.2.0 
linter-eslint 8.2.1 
linter-js-standard 3.9.1 
linter-ui-default 1.6.2 
nord-atom-syntax 0.8.0 
nord-atom-ui 0.11.0 
prettier-atom 0.35.1 
```

**Comment by Stanzilla** [comment] 2017-07-18 05:57
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0-beta3 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 8.1 Pro with Media Center
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package 0.86.0


### Stack Trace

Uncaught TypeError: Cannot read property 'openScopes' of undefined

```
At C:\Users\Benjamin\AppData\Local\atom\app-1.19.0-beta3\resources\app\node_modules\bracket-matcher\lib\tag-finder.js:53

TypeError: Cannot read property 'openScopes' of undefined
    at TagFinder.module.exports.TagFinder.scopesForPositionMatchRegex (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:53:22)
    at TagFinder.module.exports.TagFinder.isCursorOnTag (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:43:19)
    at TagFinder.module.exports.TagFinder.findMatchingTags (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:172:16)
    at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:106:35)
    at ~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:3:59
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/event-kit/lib/emitter.js:141:28)
    at TokenizedBuffer.module.exports.TokenizedBuffer.markTokenizationComplete (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/src/tokenized-buffer.js:252:22)
    at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/src/tokenized-buffer.js:246:21)
    at ~/AppData/Local/atom/app-1.19.0-beta3/resources/app/src/tokenized-buffer.js:206:26
    at ~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/underscore/underscore.js:666:47
```

### Commands

```
     -1:13.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -0:30.3.0 settings-view:open (a.btn-issue.btn.btn-error)
```

### Non-Core Packages

```
atom-increment 0.3.4 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
auto-detect-indentation 1.3.0 
autocomplete-html-entities 0.1.0 
autocomplete-php 0.3.7 
color-picker 2.2.5 
editorconfig 2.2.2 
file-icons 2.1.8 
file-watcher 1.1.0 
indent-guide-improved 1.4.13 
intentions 1.1.2 
language-batch 0.4.0 
language-blade 0.32.0 
language-cmake 0.3.0 
language-dots 0.0.4 
language-lua 0.9.11 
language-lua-wow 0.2.0 
language-powershell 4.0.0 
language-toc-wow 0.2.0 
less-than-slash 0.17.0 
linter 2.2.0 
linter-luacheck 2.0.1 
linter-php 1.3.2 
linter-ui-default 1.6.2 
linter-ui-plus 0.3.2 
linter-xo 0.23.1 
MagicPython 1.0.10 
markdown-scroll-sync 2.1.2 
minimap 4.28.3 
minimap-plus 4.29.2 
one-dark-vivid-syntax 1.8.0 
pigments 0.39.1 
pretty-json 1.6.3 
project-plus 1.0.0 
revert-buffer 0.5.0 
sort-lines 0.14.0 
space-tab 0.4.2 
sync-settings 0.8.2 
tool-bar 1.1.0 
tool-bar-almighty 0.8.2 
trailing-spaces 0.4.0 
```

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0-beta3 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 8.1 Pro with Media Center
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package 0.86.0


### Stack Trace

Uncaught TypeError: Cannot read property 'openScopes' of undefined

```
At C:\Users\Benjamin\AppData\Local\atom\app-1.19.0-beta3\resources\app\node_modules\bracket-matcher\lib\tag-finder.js:53

TypeError: Cannot read property 'openScopes' of undefined
    at TagFinder.module.exports.TagFinder.scopesForPositionMatchRegex (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:53:22)
    at TagFinder.module.exports.TagFinder.isCursorOnTag (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:43:19)
    at TagFinder.module.exports.TagFinder.findMatchingTags (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:172:16)
    at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:106:35)
    at ~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:3:59
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/event-kit/lib/emitter.js:141:28)
    at TokenizedBuffer.module.exports.TokenizedBuffer.markTokenizationComplete (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/src/tokenized-buffer.js:252:22)
    at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/src/tokenized-buffer.js:246:21)
    at ~/AppData/Local/atom/app-1.19.0-beta3/resources/app/src/tokenized-buffer.js:206:26
    at ~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/underscore/underscore.js:666:47
```

### Commands

```
     -1:13.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -0:30.3.0 settings-view:open (a.btn-issue.btn.btn-error)
```

### Non-Core Packages

```
atom-increment 0.3.4 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
auto-detect-indentation 1.3.0 
autocomplete-html-entities 0.1.0 
autocomplete-php 0.3.7 
color-picker 2.2.5 
editorconfig 2.2.2 
file-icons 2.1.8 
file-watcher 1.1.0 
indent-guide-improved 1.4.13 
intentions 1.1.2 
language-batch 0.4.0 
language-blade 0.32.0 
language-cmake 0.3.0 
language-dots 0.0.4 
language-lua 0.9.11 
language-lua-wow 0.2.0 
language-powershell 4.0.0 
language-toc-wow 0.2.0 
less-than-slash 0.17.0 
linter 2.2.0 
linter-luacheck 2.0.1 
linter-php 1.3.2 
linter-ui-default 1.6.2 
linter-ui-plus 0.3.2 
linter-xo 0.23.1 
MagicPython 1.0.10 
markdown-scroll-sync 2.1.2 
minimap 4.28.3 
minimap-plus 4.29.2 
one-dark-vivid-syntax 1.8.0 
pigments 0.39.1 
pretty-json 1.6.3 
project-plus 1.0.0 
revert-buffer 0.5.0 
sort-lines 0.14.0 
space-tab 0.4.2 
sync-settings 0.8.2 
tool-bar 1.1.0 
tool-bar-almighty 0.8.2 
trailing-spaces 0.4.0 
```

**Comment by rsese** [comment] 2017-07-19 17:47
Re-opening /cc https://github.com/atom/bracket-matcher/issues/292#issuecomment-311497372

**Comment by dflock** [comment] 2017-08-10 01:03
Started happening for me on Atom 1.20.0-beta.

**Comment by Lazny** [comment] 2017-08-10 05:11
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package 0.86.0


### Stack Trace

Failed to activate the bracket-matcher package

```
At Cannot read property 'openScopes' of undefined

TypeError: Cannot read property 'openScopes' of undefined
    at TagFinder.module.exports.TagFinder.scopesForPositionMatchRegex (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:55:28)
    at TagFinder.module.exports.TagFinder.isCursorOnTag (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:45:25)
    at TagFinder.module.exports.TagFinder.findMatchingTags (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:174:22)
    at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:128:41)
    at BracketMatcherView.updateMatch (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:3:65)
    at new BracketMatcherView (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:92:18)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/main.js:16:15
    at Workspace.observeTextEditors (~/AppData/Local/atom/app-1.19.0/resources/app/src/workspace.js:717:15)
    at Object.activate (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/main.js:12:35)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:253:25)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.19.0/resources/app/src/package-manager.js:645:40)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.19.0/resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (~/AppData/Local/atom/app-1.19.0/resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (~/AppData/Local/atom/app-1.19.0/resources/app/src/package-manager.js:603:52)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/atom-environment.js:843:36
```

### Commands

```
     -1:58.7.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -1:58 emmet:insert-formatted-line-break-only (input.hidden-input)
     -1:58 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
anodyne-dark-syntax 0.2.1 
atom-beautify 0.30.4 
atom-dark-fusion-syntax 2.2.0 
atom-typescript 11.0.6 
base16-ocean-dark-syntax-theme 0.1.10 
base16-syntax 1.8.1 
busy-signal 1.4.3 
emmet 2.4.3 
file-icons 2.1.10 
fonts 3.0.2 
gpp-compiler 3.0.7 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.6.4 
pigments 0.40.2 
spacegray-atom-dark-syntax 1.3.2 
spacegray-dark-neue-ui 1.7.1 
terminal-plus 0.14.5 
tree-view-git-status 1.4.0 
```

**Comment by Lazny** [comment] 2017-08-10 05:12
how can this be solved?

**Comment by richardturnerdeveloper** [comment] 2017-08-10 06:24
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.11.3
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package 0.86.0


### Stack Trace

Failed to activate the bracket-matcher package

```
At Cannot read property 'openScopes' of undefined

TypeError: Cannot read property 'openScopes' of undefined
    at TagFinder.module.exports.TagFinder.scopesForPositionMatchRegex (/Applications/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/tag-finder.js:55:28)
    at TagFinder.module.exports.TagFinder.isCursorOnTag (/Applications/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/tag-finder.js:45:25)
    at TagFinder.module.exports.TagFinder.findMatchingTags (/Applications/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/tag-finder.js:174:22)
    at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (/Applications/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:128:41)
    at BracketMatcherView.updateMatch (/Applications/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:3:65)
    at new BracketMatcherView (/Applications/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:92:18)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/main.js:16:15
    at Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:717:15)
    at Object.activate (/Applications/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/main.js:12:35)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:603:52)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:843:36
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by scholtzm** [comment] 2017-08-10 07:37
Started happening after updating to stable v1.19.0.

**Comment by ptpaterson** [comment] 2017-08-10 13:30
I tried to nuke the node_modules folder from inside of Atom, but ran into admin privilege problems.  I thought that was weird enough, so I rebooted my machine.  When I opened Atom I received this error and a similar stack trace `At Cannot read property 'openScopes' of undefined`.

I deleted node_modules, from inside of atom, then restarted Atom.  I am no longer getting the error.  

### Community Packages Installed
```
language-vue
platformio-ide-terminal
seti-icons
```

**Comment by Ben3eeE** [comment] 2017-08-12 12:18
Closed via https://github.com/atom/bracket-matcher/pull/308

**Closed by Ben3eeE** 2017-08-12 12:18 UTC
Labels: bug, triaged
