### ISSUE TITLE
Bracket matcher has not been working for html tags for the past couple weeks and Ctrl M is not working either

### ISSUE THREAD

**Issue by monetteContensive** [atom/bracket-matcher#373] opened 2018-11-27 13:52 UTC
Bracket matcher has not been working for html tags for the past couple weeks and Ctrl M is not working either - not sure why this suddenly stopped working, but it's really handy to have.  It's still working for Javascript tags

**Comment by rsese** [comment] 2018-11-27 21:03
Thanks for contributing!

This is a duplicate of https://github.com/atom/bracket-matcher/issues/355 - the fix will be released in Atom 1.33 and 1.34 beta.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-11-27 21:03 UTC
