### ISSUE TITLE
Latex: Uncaught TypeError: Cannot read property 'getScreenPosition' of undefined

### ISSUE THREAD

**Issue by benogle** [atom/bracket-matcher#88] opened 2014-12-10 22:35 UTC
_From @jordaorodolfo on December 6, 2014 22:12_

This error happens often whenever I'm editing an LaTeX file. Closing the tab and reopenning the document solves it momentary. 

Uncaught TypeError: Cannot read property 'getScreenPosition' of undefined

**Atom Version**: 0.153.0
**System**: linux 3.12.33-1-MANJARO
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package

_Copied from original issue: atom/atom#4428_

**Comment by peterjeliot** [comment] 2015-01-12 04:32
Here's how I reproduce it:
1. Trigger a snippet with duplicate tab stops and tab until I have multiple cursors
2. (optional) Hit escape, move the cursor around, delete some text in vim mode, etc
3. Hit tab anywhere

The entire window becomes 100% broken until I close it. After the bug triggers, all keypresses and attempts to close that tab pop up the same error.

TypeError: Cannot read property 'getScreenPosition' of undefined
  at TextEditor.module.exports.TextEditor.getCursorScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1325:34)
  at TextEditor.module.exports.TextEditor.isFoldedAtCursorRow (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2578:44)
  at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (/Applications/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:111:23)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:94:26
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app/src/cursor.js:70:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.destroyed (/Applications/Atom.app/Contents/Resources/app/src/marker.js:264:20)
  at /Applications/Atom.app/Contents/Resources/app/src/marker.js:51:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.destroy (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker.js:318:20)
  at Marker.module.exports.Marker.destroy (/Applications/Atom.app/Contents/Resources/app/src/marker.js:62:25)
  at Selection.module.exports.Selection.destroy (/Applications/Atom.app/Contents/Resources/app/src/selection.js:62:26)
  at SnippetExpansion.module.exports.SnippetExpansion.setTabStopIndex (/Applications/Atom.app/Contents/Resources/app/node_modules/snippets/lib/snippet-expansion.js:120:21)
  at SnippetExpansion.module.exports.SnippetExpansion.goToNextTabStop (/Applications/Atom.app/Contents/Resources/app/node_modules/snippets/lib/snippet-expansion.js:86:18)
  at Object.module.exports.goToNextTabStop (/Applications/Atom.app/Contents/Resources/app/node_modules/snippets/lib/snippets.js:397:43)
  at atom-text-editor.subscriptions.add.atom.commands.add.snippets:next-tab-stop (/Applications/Atom.app/Contents/Resources/app/node_modules/snippets/lib/snippets.js:56:25)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)

**Comment by brunetton** [comment] 2015-01-12 10:44
I can confirm, the bug is still present in 0.169. I can't reproduce it exactely, and I didn't understand well Peter sentence "Trigger a snippet with duplicate tab stops and tab until I have multiple cursors", so I can't be sure to try the same thing he did, but it definitely doen't have nothing todo with a Latex problem.
It comes while editing Python code, and using multiple-cursor snippet.
I'll try to find a way to reproduce it.

Atom v0.169 / Debian stable, no --safe mode

**Comment by brunetton** [comment] 2015-01-12 11:02
Ok, I got it :

# Steps to reproduce :

## Define those two snipets 
	'.source.python':
	'Import pformat and pp':
		'prefix': 'ipp'
		'body': '${2:from pprint import pformat}\nprint u"$1: ", pformat($1)$3'
	'Print debug':
		'prefix': 'pp'
		'body': 'print u"$1: ", pformat($1)'

## In a Python file, do those manipulations

ipp <tab> <esc> [new line]
pp <tab>

When [new line] means: go to a new edit line, typically ctrl-return

**Comment by brunetton** [comment] 2015-01-13 11:21
I correct myself: it's not a multi-line snippet problem, but a multi-stop snippet (probably what Peter means).

# Steps to reproduce :

## Define a multi-stop snippet
    '.source.python':
        'Test':
            'prefix': 'tt'
            'body': '$1=$1$2'

## In a Python file, do those manipulations

```
tt <tab> <esc>
tt <tab>
```
Exception should appear

**Comment by peterjeliot** [comment] 2015-01-14 04:20
Apologies for the subpar reproduction instructions.

Here is a snippet that triggers this behavior. I had forgotten that I'd used nested tabstops.

```
{
  ".source.ruby": {
    "def destroy ...": {
      "prefix": "defdestroy",
      "body": """
        def destroy
          ${1:link} = ${2:Link}.find(params[:id])
          ${1:link}.destroy
          redirect_to ${3:${1:link}s}_url
        end
        $0
      """
    }
  }
}
```

1. Open a file, select 'Ruby' for the language on the bottom-right of the window.
2. Type "defdestroy", tab, escape, down, tab

Interestingly, I just found another different exception from this set of keystrokes
1. Open a file, select 'Ruby' for the language on the bottom-right of the window.
2. Type "defdestroy", tab, escape, tab
3. Click in the window

**Comment by propersquid** [comment] 2015-01-17 05:02
I get this error too.

OS: Linux Mint 17 64 bit

Reproduction:
1. Create a C++ file
2. Type once (then tab)
3. Type cl (then tab)
4. Error should pop up from that.

Stack trace:
```
/usr/share/atom/resources/app/src/text-editor.js:1357
TypeError: Cannot read property 'getScreenPosition' of undefined
  at TextEditor.module.exports.TextEditor.getCursorScreenPosition (/usr/share/atom/resources/app/src/text-editor.js:1357:34)
  at TextEditor.module.exports.TextEditor.isFoldedAtCursorRow (/usr/share/atom/resources/app/src/text-editor.js:2617:44)
  at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (/usr/share/atom/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:111:23)
  at /usr/share/atom/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:94:26
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at /usr/share/atom/resources/app/src/cursor.js:70:25
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.destroyed (/usr/share/atom/resources/app/src/marker.js:264:20)
  at /usr/share/atom/resources/app/src/marker.js:51:24
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/text-buffer/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.destroy (/usr/share/atom/resources/app/node_modules/text-buffer/lib/marker.js:318:20)
  at Marker.module.exports.Marker.destroy (/usr/share/atom/resources/app/src/marker.js:62:25)
  at Selection.module.exports.Selection.destroy (/usr/share/atom/resources/app/src/selection.js:62:26)
  at SnippetExpansion.module.exports.SnippetExpansion.setTabStopIndex (/usr/share/atom/resources/app/node_modules/snippets/lib/snippet-expansion.js:120:21)
  at SnippetExpansion.module.exports.SnippetExpansion.goToNextTabStop (/usr/share/atom/resources/app/node_modules/snippets/lib/snippet-expansion.js:86:18)
  at Object.module.exports.goToNextTabStop (/usr/share/atom/resources/app/node_modules/snippets/lib/snippets.js:414:43)
  at atom-text-editor.subscriptions.add.atom.commands.add.snippets:next-tab-stop (/usr/share/atom/resources/app/node_modules/snippets/lib/snippets.js:56:25)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:170:20)
```

**Comment by benogle** [comment] 2015-02-26 23:56
I'm on current master. This is not reproducable, but this is what happened

1. In a spec
1. I wrote `req` tab to expand the require snippet
1. did some stuff I dont remember
1. typed `be` then tab to expand the snippet
1. this error.

Trying to figure out legit steps now

**Atom Version**: 0.185.0-fdda26a
**System**: Mac OS X 10.9.5
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package, v0.71.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getScreenPosition' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1393

TypeError: Cannot read property 'getScreenPosition' of undefined
  at TextEditor.module.exports.TextEditor.getCursorScreenPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1393:34)
  at TextEditor.module.exports.TextEditor.isFoldedAtCursorRow (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2652:44)
  at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (/Applications/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:111:23)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:94:26
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app/src/cursor.js:70:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.destroyed (/Applications/Atom.app/Contents/Resources/app/src/marker.js:264:20)
  at /Applications/Atom.app/Contents/Resources/app/src/marker.js:51:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.destroy (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/marker.js:318:20)
  at Marker.module.exports.Marker.destroy (/Applications/Atom.app/Contents/Resources/app/src/marker.js:62:25)
  at Selection.module.exports.Selection.destroy (/Applications/Atom.app/Contents/Resources/app/src/selection.js:62:26)
  at SnippetExpansion.module.exports.SnippetExpansion.setTabStopIndex (/Applications/Atom.app/Contents/Resources/app/node_modules/snippets/lib/snippet-expansion.js:120:21)
  at SnippetExpansion.module.exports.SnippetExpansion.goToNextTabStop (/Applications/Atom.app/Contents/Resources/app/node_modules/snippets/lib/snippet-expansion.js:86:18)
  at Object.module.exports.goToNextTabStop (/Applications/Atom.app/Contents/Resources/app/node_modules/snippets/lib/snippets.js:419:43)
  at atom-text-editor.subscriptions.add.atom.commands.add.snippets:next-tab-stop (/Applications/Atom.app/Contents/Resources/app/node_modules/snippets/lib/snippets.js:56:25)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:182:20)

```

### Commands

```
     -0:45.8 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:45.6 core:save (atom-text-editor.editor.is-focused)
 10x -0:13.1 core:move-down (atom-text-editor.editor.is-focused)
     -0:11.5 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:11.4 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:11.1 core:copy (atom-text-editor.editor.is-focused)
 10x -0:10.8 core:move-up (atom-text-editor.editor.is-focused)
     -0:09.2 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:09.1 editor:newline (atom-text-editor.editor.is-focused)
     -0:08.7 core:backspace (atom-text-editor.editor.is-focused)
     -0:08.5 core:paste (atom-text-editor.editor.is-focused)
  2x -0:08.2 editor:newline (atom-text-editor.editor.is-focused)
  8x -0:03.7 core:move-up (atom-text-editor.editor.is-focused)
     -0:02.6 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:02.4 editor:newline (atom-text-editor.editor.is-focused)
     -0:00.5 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autosave",
      "color-picker",
      "css-color-highlighting",
      "font-viewer",
      "atom-css-comb",
      "live-archive",
      "atomatigit",
      "minimap",
      "autocomplete"
    ],
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-css, v0.2.0
autocomplete-html, v0.2.0
autocomplete-plus, v2.2.0
autocomplete-snippets, v1.0.1
block-travel, v1.0.2
comment-newline, v0.0.0
error-generator, v0.0.0
git-experiment, v0.0.0
welcome, v0.23.0

# Dev
comment-newline, v0.0.0
git-experiment, v0.0.0
metrics, v0.45.0
notifications, v0.30.0
snippets, v0.76.0
welcome, v0.23.0
```

**Comment by dander401** [comment] 2015-08-31 19:12
Sorry for lack of proper format... Im very new to this and not sure what really to do.... 
I cannot reproduce this on command, but have been affected when the following criteria is met. 
    2 Panes with the same file open at different positions
    give another application focus
    return focus to Atom
    change active pane
    undo a change
   
Once it starts, I cannot type or change panes and have to do a window reload. 

Just curious. In the future, how can I be more helpful? 


**Atom Version**: 1.0.9
**System**: Mac OS X 10.10.5
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package, v0.76.0


### Stack Trace

Uncaught TypeError: Cannot read property 'getScreenPosition' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1371

TypeError: Cannot read property 'getScreenPosition' of undefined
  at TextEditor.module.exports.TextEditor.getCursorScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1371:34)
  at TextEditor.module.exports.TextEditor.isFoldedAtCursorRow (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2575:44)
  at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher-view.js:111:23)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher-view.js:40:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:236:32
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at DisplayBuffer.module.exports.DisplayBuffer.emitDidChange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:313:20)
  at DisplayBuffer.module.exports.DisplayBuffer.updateScreenLines (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1592:19)
  at DisplayBuffer.module.exports.DisplayBuffer.handleTokenizedBufferChange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1551:12)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:5:61
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TokenizedBuffer.module.exports.TokenizedBuffer.handleBufferChange (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:404:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:64:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:648:20)
  at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:802:16)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:771:14)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1168:26)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:781:24
  at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2044:43)
  at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2010:35)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:779:19)
  at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:742:19)
  at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
  at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:435:35)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:61)

```

### Commands

```
     -0:06.3.0 git-diff-details:close-git-diff-details (atom-text-editor.editor.is-focused)
     -0:06.3.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:05.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:04.2.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:04.2.0 git-diff-details:close-git-diff-details (atom-text-editor.editor.is-focused)
     -0:04.2.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:04.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:04.0 git-diff-details:close-git-diff-details (atom-text-editor.editor.is-focused)
     -0:04.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:03.8.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:03.8.0 git-diff-details:close-git-diff-details (atom-text-editor.editor.is-focused)
     -0:03.8.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:03.7.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:03.7.0 git-diff-details:close-git-diff-details (atom-text-editor.editor.is-focused)
     -0:03.7.0 core:cancel (atom-text-editor.editor.is-focused)
  2x -0:02.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "file-icons",
      "linter-manager",
      "todo-manager",
      "fonts",
      "minimap-highlight-selected",
      "vim-mode",
      "autocomplete-snippets",
      "snippets"
    ],
    "ignoredNames": [
      ".bin",
      "META*",
      ".DS_Store",
      "dist",
      "*.jar",
      "target",
      "*.iml",
      "*.sublime*",
      "node*"
    ],
    "projectHome": "/Users/davidanderson/Projects/wstamp",
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "audioBeep": false,
    "excludeVcsIgnoredPaths": false
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.11
autoclose-html, v0.18.0
bottom-dock, v0.3.2
custom-invisibles, v0.1.2
git-diff-details, v0.20.0
linter, v1.4.3
linter-csslint, v1.0.5
linter-jshint, v1.1.5
linter-less, v2.1.0
minimap, v4.13.2
minimap-bookmarks, v0.1.0
minimap-codeglance, v0.4.0
minimap-find-and-replace, v4.3.0
minimap-hide, v0.3.0
minimap-linter, v1.0.0
move-panes, v0.2.0
pigments, v0.13.0
project-manager, v2.0.1
seti-syntax, v0.4.0
seti-ui, v0.8.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-08-31 19:52
> Just curious. In the future, how can I be more helpful?

@dander401 You already did pretty well with how you reported the bug - most people just leave the "steps to reproduce" section blank.

**Comment by zwacky** [comment] 2015-09-07 13:56
[Enter steps to reproduce below:]

1. (not 100% sure) think i was tabbing between tabs with cmd+[1-3] and then did cmd-z

**Atom Version**: 1.0.10
**System**: Mac OS X 10.10.5
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package, v0.76.0


### Stack Trace

Uncaught TypeError: Cannot read property 'getScreenPosition' of undefined

```
At /Users/zwacky/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1371

TypeError: Cannot read property 'getScreenPosition' of undefined
  at TextEditor.module.exports.TextEditor.getCursorScreenPosition (/Users/zwacky/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1371:34)
  at TextEditor.module.exports.TextEditor.isFoldedAtCursorRow (/Users/zwacky/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2575:44)
  at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (/Users/zwacky/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher-view.js:111:23)
  at /Users/zwacky/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher-view.js:94:26
  at Emitter.module.exports.Emitter.emit (/Users/zwacky/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Users/zwacky/Downloads/Atom.app/Contents/Resources/app.asar/src/cursor.js:66:25
  at Emitter.module.exports.Emitter.emit (/Users/zwacky/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.destroyed (/Users/zwacky/Downloads/Atom.app/Contents/Resources/app.asar/src/marker.js:232:20)
  at /Users/zwacky/Downloads/Atom.app/Contents/Resources/app.asar/src/marker.js:37:24
  at Emitter.module.exports.Emitter.emit (/Users/zwacky/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.destroy (/Users/zwacky/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:256:20)
  at MarkerStore.module.exports.MarkerStore.restoreFromSnapshot (/Users/zwacky/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-store.js:219:20)
  at TextBuffer.module.exports.TextBuffer.undo (/Users/zwacky/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:737:26)
  at /Users/zwacky/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1152:31
  at TextEditor.module.exports.TextEditor.mergeSelections (/Users/zwacky/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2048:18)
  at TextEditor.module.exports.TextEditor.avoidMergingSelections (/Users/zwacky/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2030:35)
  at TextEditor.module.exports.TextEditor.undo (/Users/zwacky/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1150:12)
  at TextEditor.atom.commands.add.stopEventPropagation.core:undo (/Users/zwacky/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:333:19)
  at atom-text-editor.newCommandListeners.(anonymous function) (/Users/zwacky/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:301:32)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/zwacky/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Users/zwacky/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/zwacky/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/zwacky/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Users/zwacky/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
  2x -1:00.2.0 core:copy (atom-text-editor.editor.is-focused)
  2x -0:39.3.0 core:cut (atom-text-editor.editor.is-focused)
     -0:35.9.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:16.9.0 core:undo (atom-text-editor.editor.is-focused)
     -0:15.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:12.9.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
  2x -0:12.5.0 core:select-left (atom-text-editor.editor.is-focused)
     -0:12 core:select-right (atom-text-editor.editor.is-focused)
     -0:11.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:11.4.0 core:close (atom-text-editor.editor.is-focused)
  2x -0:10.6.0 core:undo (atom-text-editor.editor.is-focused)
  5x -0:09.2.0 core:redo (atom-text-editor.editor.is-focused)
     -0:05.6.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:03.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.9.0 core:undo (atom-text-editor.editor.is-focused)
     -0:01.6.0 core:redo (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-jshint"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-pair, v2.0.10
color-picker, v2.0.11
compare-files, v0.6.2
emmet, v2.3.12
imdone-atom, v1.1.37
merge-conflicts, v1.3.5
symbols-tree-view, v0.9.3

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-09-25 03:45
No further reports, closing.

**Closed by 50Wliu** 2016-09-25 03:45 UTC
Labels: bug, uncaught-exception
