### ISSUE TITLE
Addon not working any more

### ISSUE THREAD

**Issue by monetteContensive** [atom/bracket-matcher#368] opened 2018-11-20 13:56 UTC
This addon used to work fine in Atom, but for the past week or so, it hasn't been working... not sure why.  The matching tags won't highlight and Ctrl M doesn't do anything.

**Comment by Arcanemagus** [comment] 2018-11-20 17:22
Thanks for taking the time to contribute!

Although you didn't specify the language or fill out the template this looks to be a duplicate of https://github.com/atom/bracket-matcher/issues/355, which will be fixed in https://github.com/atom/bracket-matcher/pull/367. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2018-11-20 17:22 UTC
