### ISSUE TITLE
As soon I open Atom It throw this error

### ISSUE THREAD

**Issue by rangolee302** [atom/bracket-matcher#309] opened 2017-08-12 08:05 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package 0.86.0

### Stack Trace

Failed to activate the bracket-matcher package

```
At Cannot read property 'openScopes' of undefined

TypeError: Cannot read property 'openScopes' of undefined
    at TagFinder.module.exports.TagFinder.scopesForPositionMatchRegex (C:/Users/pcuser3/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:55:28)
    at TagFinder.module.exports.TagFinder.isCursorOnTag (C:/Users/pcuser3/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:45:25)
    at TagFinder.module.exports.TagFinder.findMatchingTags (C:/Users/pcuser3/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:174:22)
    at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (C:/Users/pcuser3/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:128:41)
    at BracketMatcherView.updateMatch (C:/Users/pcuser3/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:3:65)
    at new BracketMatcherView (C:/Users/pcuser3/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:92:18)
    at C:/Users/pcuser3/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/main.js:16:15
    at Workspace.observeTextEditors (C:/Users/pcuser3/AppData/Local/atom/app-1.19.0/resources/app/src/workspace.js:717:15)
    at Object.activate (C:/Users/pcuser3/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/main.js:12:35)
    at Package.module.exports.Package.activateNow (C:/Users/pcuser3/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:253:25)
    at C:/Users/pcuser3/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (C:/Users/pcuser3/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:99:21)
    at C:/Users/pcuser3/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (C:/Users/pcuser3/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (C:/Users/pcuser3/AppData/Local/atom/app-1.19.0/resources/app/src/package-manager.js:645:40)
    at C:/Users/pcuser3/AppData/Local/atom/app-1.19.0/resources/app/src/package-manager.js:377:25
    at C:/Users/pcuser3/AppData/Local/atom/app-1.19.0/resources/app/src/config.js:644:26
    at Function.module.exports.Emitter.simpleDispatch (C:/Users/pcuser3/AppData/Local/atom/app-1.19.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (C:/Users/pcuser3/AppData/Local/atom/app-1.19.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (C:/Users/pcuser3/AppData/Local/atom/app-1.19.0/resources/app/src/config.js:835:35)
    at Config.module.exports.Config.setRawValue (C:/Users/pcuser3/AppData/Local/atom/app-1.19.0/resources/app/src/config.js:621:25)
    at Config.module.exports.Config.set (C:/Users/pcuser3/AppData/Local/atom/app-1.19.0/resources/app/src/config.js:236:20)
    at Config.module.exports.Config.removeAtKeyPath (C:/Users/pcuser3/AppData/Local/atom/app-1.19.0/resources/app/src/config.js:386:18)
    at Package.module.exports.Package.enable (C:/Users/pcuser3/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:84:32)
    at PackageManager.module.exports.PackageManager.enablePackage (C:/Users/pcuser3/AppData/Local/atom/app-1.19.0/resources/app/src/package-manager.js:188:20)
    at HTMLButtonElement.enablementButtonClickHandler (C:/Users/pcuser3/AppData/Local/atom/app-1.19.0/resources/app/node_modules/settings-view/lib/package-card.js:361:31)
```

### Commands

```
     -1:35.1.0 core:backspace (input.hidden-input)
     -1:34.8.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.13 
SFTP-deployment 1.0.2 
```

**Comment by Ben3eeE** [comment] 2017-08-12 08:12
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/bracket-matcher/issues/292. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2017-08-12 08:12 UTC
Labels: duplicate
