### ISSUE TITLE
When matching a closing bracket, the previous character should be used

### ISSUE THREAD

**Issue by WalterGR** [atom/bracket-matcher#206] opened 2016-01-17 23:50 UTC
It's fairly customary to match closing brackets based on the previous character - i.e. the character the user just typed.

Atom matches based on the current character - i.e. the character the user may or may not type in the future:

![atom-highlights-next-bracket--resized](https://cloud.githubusercontent.com/assets/380880/12380762/8f621f84-bd2f-11e5-9cf0-65bf9bf76e94.png)

Most other editors do look at the previous character.

Sublime Text:

![atom-highlights-next-bracket--sublime--resized](https://cloud.githubusercontent.com/assets/380880/12380747/67e3e316-bd2f-11e5-9e86-df183307c056.png)

Emacs:

![atom-highlights-next-bracket--emacs--resized](https://cloud.githubusercontent.com/assets/380880/12380763/a033600c-bd2f-11e5-8c10-379261722095.png)

IntelliJ:

![atom-highlights-next-bracket--intellij--resized](https://cloud.githubusercontent.com/assets/380880/12380764/a4eb1fd6-bd2f-11e5-8262-27bdc9bdd0c6.png)

Visual Studio:

![atom-highlights-next-bracket--visual-studio--resized](https://cloud.githubusercontent.com/assets/380880/12380765/aa4d746a-bd2f-11e5-959b-7dc5622c85f9.png)

Notepad++ (popular on Windows):

![atom-highlights-next-bracket--notepadpp--resized](https://cloud.githubusercontent.com/assets/380880/12380851/524fac18-bd31-11e5-987b-b710cf8296ce.png)

**Comment by WalterGR** [comment] 2016-01-22 00:46
I've done the work locally to change this behavior.

Is this something that the Atom devs are willing to change, or willing to make controllable via a setting?

Atom's current behavior isn't cut out programming in Lisp-derived languages.

**Comment by 50Wliu** [comment] 2016-09-25 03:41
This is a duplicate of #116 - feel free to subscribe there for updates.

@WalterGR Please create that PR if you've already done the work locally.

**Closed by 50Wliu** 2016-09-25 03:41 UTC
Labels: feedback
