### ISSUE TITLE
Bracket swallowing not working consistently

### ISSUE THREAD

**Issue by codeHatcher** [atom/bracket-matcher#224] opened 2016-04-04 20:14 UTC
I constantly find duplicate brackets appearing because the swallowing is not working correctly. Here is in an example in a C# project.

https://gyazo.com/cc676f78117dfb32a77d056e87bc9112

**Comment by codeHatcher** [comment] 2016-04-04 20:14
I have a US keyboard, I see that was an issue before with international keyboards

**Comment by smparekh** [comment] 2016-08-08 15:24
+1, bracket or quote swallowing not working for me as well.

**Comment by apazzolini** [comment] 2016-08-11 17:25
I see this too on a US MacBook Pro keyboard. For me, it only happens when autocompletion adds the brackets on a function call:

![](https://d3vv6lp55qjaqc.cloudfront.net/items/3Y0F1f1a362P2q2T0T1H/Screen%20Recording%202016-08-11%20at%2012.24%20PM.gif)

**Comment by 50Wliu** [comment] 2016-09-25 03:16
This is a duplicate of #28 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-09-25 03:16 UTC
