### ISSUE TITLE
Uncaught TypeError: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by gordonjb** [atom/bracket-matcher#137] opened 2015-05-21 13:02 UTC
[Enter steps to reproduce below:]

1.Took an XML file with no errors, removed a bracket (>) to create an error. XML Lint error appeared.
2. Hit Ctrl - Z to undo, recieved this error.

**Atom Version**: 0.200.0
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package, v0.74.0

### Stack Trace

Uncaught TypeError: Cannot read property 'start' of undefined

```
At D:\Users\GJBonthron\AppData\Local\atom\app-0.200.0\resources\app.asar\node_modules\text-buffer\lib\range.js:35

TypeError: Cannot read property 'start' of undefined
  at Function.module.exports.Range.fromObject (D:\Users\GJBonthron\AppData\Local\atom\app-0.200.0\resources\app.asar\node_modules\text-buffer\lib\range.js:35:31)
  at DisplayBuffer.module.exports.DisplayBuffer.screenRangeForBufferRange (D:\Users\GJBonthron\AppData\Local\atom\app-0.200.0\resources\app.asar\src\display-buffer.js:884:27)
  at Marker.module.exports.Marker.getScreenRange (D:\Users\GJBonthron\AppData\Local\atom\app-0.200.0\resources\app.asar\src\marker.js:136:33)
  at TextEditorPresenter.module.exports.TextEditorPresenter.updateHighlightState (D:\Users\GJBonthron\AppData\Local\atom\app-0.200.0\resources\app.asar\src\text-editor-presenter.js:1599:22)
  at TextEditorPresenter.module.exports.TextEditorPresenter.didDestroyDecoration (D:\Users\GJBonthron\AppData\Local\atom\app-0.200.0\resources\app.asar\src\text-editor-presenter.js:1451:14)
  at D:\Users\GJBonthron\AppData\Local\atom\app-0.200.0\resources\app.asar\src\text-editor-presenter.js:1369:24
  at Emitter.module.exports.Emitter.emit (D:\Users\GJBonthron\AppData\Local\atom\app-0.200.0\resources\app.

**Comment by andya9** [comment] 2015-05-30 14:21
I can reproduce this too. It doesn’t seem to happen when linter-xmllint is disabled

**Comment by andya9** [comment] 2015-05-30 17:32
Update: and it happens only when clicking somewhere else before coming back to fix it; so:
1. \<section
2. if i immediately close it, everything works fine. If I edit something on a different line first, and then come back to fix this, the error pops up.

**Comment by fburleigh** [comment] 2015-06-04 17:38
I also see this -- the editor gets stuck after XML Linter tells me that my XML is malformed.

**Comment by andya9** [comment] 2015-06-04 20:53
@fburleigh I opened an issue on [main Atom repo](https://github.com/atom/atom/issues/7077), as bracket-matcher is not the only affected package

**Comment by izuzak** [comment] 2015-06-08 20:45
Was just playing with linter-xmllint and was able to trigger the exception reported here and other exceptions reported in https://github.com/atom/atom/issues/7077. I was also able to trigger some strange behavior in which the cursor would get "stuck" -- pressing `delete` or trying to move it didn't work until I manually clicked somewhere else in the editor. I don't have exact steps to reproduce unfortunately, as @andya9 mentioned -- it happens randomly after triggering xmllint errors and undoing.

@nathansobo You were looking at some marker-related stuff in https://github.com/atom/atom/issues/6899 which sounds kinda similar to this (markers being destroyed?). Wondering if you'd want to take a look at this as well since it's possible to trigger the problem with a few minutes of playing with an XML file?

**Comment by izuzak** [comment] 2015-06-10 20:56
Fixed by https://github.com/atom/text-buffer/issues/75, see https://github.com/atom/atom/issues/7077#issuecomment-110904293 for more details.

**Closed by izuzak** 2015-06-10 20:56 UTC
Labels: uncaught-exception
