### ISSUE TITLE
Highlighted matching bracket is in string!

### ISSUE THREAD

**Issue by aryzing** [atom/bracket-matcher#226] opened 2016-04-08 10:09 UTC
Hi, I was just practicing some JS by re-implementing JSON.stringify when I noticed that one of the reported matching brackets was actually within a string. See example. Note: work in progress!
```javascript
var stringifyJSON = function(val) {
  if (val === true) {
    return "true";
  } else if (val === false) {
    return "false";
  } else if (typeof val === "number") {
    return '' + val;
  } else if (val === null) {
    return 'null';
  } else if (typeof val === 'string') {
    return '"' + val + '"';
  } else if (Array.isArray(val)) {

  } else if (typeof val === 'object') { // msg2: ...should match opening one...
    var result = '{';             // msg3: ...instead matches this opening one.
    for (element in val) {
      if (stringifyJSON(val[element]) !== undefined) {
        result += element + ':' + stringifyJSON(val(element)) + ',';
      }
    }
    if (result.slice(-1) === ',') {
      result = result.slice(0, -1);
    } else {
      result = undefined;
    }
    return result;
  } else {                     // msg1: Closing brace on this line...
    return undefined;
  }
};
```

**Comment by 50Wliu** [comment] 2016-04-08 13:25
This is a duplicate of #78 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-04-08 13:25 UTC
