### ISSUE TITLE
Incorrect opening element is highlighted on multi-line elements

### ISSUE THREAD

**Issue by ugultopu** [atom/bracket-matcher#336] opened 2017-12-11 02:29 UTC
# Version Information
OS: macOS High Sierra
Atom: 1.22.1
Electron: 1.6.15
Chrome: 56.0.2924.87
Node: 7.4.0

# Steps to Reproduce
![screen shot 2017-12-10 at 22 27 28](https://user-images.githubusercontent.com/9937444/33813340-6973d1d6-ddf9-11e7-9383-39b9c06d079b.png)
![screen shot 2017-12-10 at 22 27 40](https://user-images.githubusercontent.com/9937444/33813341-6d42338e-ddf9-11e7-9b8f-5c43df1c37e8.png)

# Expected Results
Correct tag is highlighted.

# Actual Results
Incorrect tag is highlighted.

**Comment by rsese** [comment] 2017-12-11 19:00
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/bracket-matcher/issues/333. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-12-11 19:00 UTC
