### ISSUE TITLE
Feature request: check bracket consistency

### ISSUE THREAD

**Issue by pvallet** [atom/bracket-matcher#234] opened 2016-06-09 08:58 UTC
Hello,

It would be nice to have a check for bracket consistency in the current file, that would display a small red message when there are more opening than closing brackets, and conversely.

It would avoid compilation errors when a bracket has been removed by mistake. 

It should stay discrete though, I don't use the auto-generation of brackets as I don't feel at ease with it, therefore I am often in the case where the count of brackets is not consistent.

It could even be more powerful, using extended Dyck language to check if the file with different types of brackets can be parsed.

**Comment by slang800** [comment] 2016-06-18 05:14
Duplicate of https://github.com/atom/bracket-matcher/issues/174

**Comment by 50Wliu** [comment] 2016-06-18 17:18
Thanks @slang800.

**Closed by 50Wliu** 2016-06-18 17:18 UTC
Labels: package-idea
