### ISSUE TITLE
[Feature Request]: growing selection in nested brackets on each CTRL+ALT+M hit

### ISSUE THREAD

**Issue by Awale** [atom/bracket-matcher#251] opened 2016-09-24 22:13 UTC
I think the following behavior would be tremendously intuitive and useful in the case of nested brackets (or pairs of any type):
1. Upon hitting CTRL+ALT+M for the first time, the text inside the innermost brackets is selected
2. Next hit adds the brackets themselves to the selection
3. Next hit adds all the text inside the next-level brackets (i.e., growing outward) 
4. etc
The thing could perhaps be done to be a cycle, so we are back at step 1 after selecting the outermost brackets with everything inside (and brackets included).

**Comment by 50Wliu** [comment] 2016-09-25 03:12
This is a duplicate of #74 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-09-25 03:12 UTC
