### ISSUE TITLE
bracket-matcher:close-tag does not skip self-closing tags

### ISSUE THREAD

**Issue by pvorona** [atom/bracket-matcher#203] opened 2016-01-02 16:22 UTC
``` js
<Scalable width={props.width} height={props.height}>
    <SimplePlot {...props} />
[Cursor here]
```

When i use command to close tag, i get `</SimplePlot>` which is already self-closed. I should get `</Scalable>` instead.

**Comment by lee-dohm** [comment] 2016-01-02 23:35
Reproduced using Atom v1.3.2 on Mac OS X 10.11.2.

**Comment by luisrudge** [comment] 2016-02-12 01:43
I'm seeing an issue that looks like this one:
![image](https://cloud.githubusercontent.com/assets/941075/12996692/3e5e4358-d119-11e5-9658-1e48de55dd15.png)

**Comment by vndmtrx** [comment] 2016-05-11 19:58
Reproduced too on Atom 1.8.0-beta3 on Windows 10.
![captura de tela 2016-05-11 16 56 33](https://cloud.githubusercontent.com/assets/596651/15194500/8e39f810-1799-11e6-82d6-b859c4dd00a0.png)

**Comment by MoritzKn** [comment] 2017-01-31 20:56
I fixed this and opened a PR: #273

**Comment by chaotyler** [comment] 2017-04-27 08:41
![image](https://cloud.githubusercontent.com/assets/4556756/25475131/54775684-2b68-11e7-92e4-331c19652f40.png)

Got this problem too

**Comment by hibiyasleep** [comment] 2017-06-27 07:10
PR #273 fixed this problem, but it seems only for 'known to self-closing' tags.

More examples here:
![2017-06-27 16 05 56](https://user-images.githubusercontent.com/5380174/27574765-98d6afc2-5b52-11e7-91de-c67695eb77a2.png)
![2017-06-27 16 05 37](https://user-images.githubusercontent.com/5380174/27574821-b9ab0784-5b52-11e7-9c92-3d04d2913f6c.png)
![2017-06-27 16 03 52](https://user-images.githubusercontent.com/5380174/27574826-bd42efec-5b52-11e7-9862-e90f3856e012.png)

ps: language set to HTML.

**Comment by MoritzKn** [comment] 2017-06-27 10:17
@hibiyasleep #273 only fixed the behavior of `bracket-matcher:close-tag`. #257 will fix the highlighting of corresponding tags.

**Comment by ungb** [comment] 2017-08-07 20:05
we found a performance regression so had to revert the change.

**Closed** 2017-08-31 18:14 UTC
Labels: bug
