### ISSUE TITLE
Autocomplete Smart Quotes setting does nothing

### ISSUE THREAD

**Issue by magic-lantern** [atom/bracket-matcher#162] opened 2015-07-23 13:34 UTC
Wether I have "Autocomplete Smart Quotes" checked or not, it always autocompletes quotes. I like bracket matching, but having to continuously delete extra quotes (and having it delete quotes for me when I don't want it to) is a pain.

**Comment by 50Wliu** [comment] 2015-07-24 00:27
Closing this as a duplicate of #158, please subscribe there for updates.

**Closed by 50Wliu** 2015-07-24 00:27 UTC
