### ISSUE TITLE
Auto-pairing for asterisk

### ISSUE THREAD

**Issue by aixnr** [atom/bracket-matcher#53] opened 2014-07-24 22:39 UTC
I think it would be cool if the core of Atom itself supports auto-pairing for asterisk for selected text, just like the one we have right now with brackets.

![asterisk2](https://cloud.githubusercontent.com/assets/1288147/3695771/72d24f62-1383-11e4-9b38-f45b4b1fba23.gif)

As for asterisk, the wrapped text is completely replaced with 1 asterisk.

![asterisk](https://i.imgur.com/qxqz2qi.gif)

**Comment by 50Wliu** [comment] 2016-09-25 03:52
This is a duplicate of #121 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-09-25 03:52 UTC
Labels: enhancement
