### ISSUE TITLE
Uncaught TypeError: Cannot read property 'openScopes' of undefined

### ISSUE THREAD

**Issue by garethallenstringer** [atom/bracket-matcher#305] opened 2017-08-10 16:34 UTC
[Enter steps to reproduce:]

1. Save .scss file with sass-autocompile
2. Get caught in infinite loop of saving
3. Close Atom
4. Get this error
5. **HAVE FILE WIPED**

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package 0.86.0

### Stack Trace

Uncaught TypeError: Cannot read property 'openScopes' of undefined

```
At C:\Users\GarethAllen-Stringer\AppData\Local\atom\app-1.19.0\resources\app\node_modules\bracket-matcher\lib\tag-finder.js:55

TypeError: Cannot read property 'openScopes' of undefined
    at TagFinder.module.exports.TagFinder.scopesForPositionMatchRegex (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:55:28)
    at TagFinder.module.exports.TagFinder.isCursorOnTag (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:45:25)
    at TagFinder.module.exports.TagFinder.findMatchingTags (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:174:22)
    at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:128:41)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:3:65
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TokenizedBuffer.module.exports.TokenizedBuffer.markTokenizationComplete (~/AppData/Local/atom/app-1.19.0/resources/app/src/tokenized-buffer.js:252:28)
    at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (~/AppData/Local/atom/app-1.19.0/resources/app/src/tokenized-buffer.js:246:27)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/tokenized-buffer.js:206:32
    at ~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/underscore/underscore.js:666:53
```

### Commands

```
     -0:14.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
atom-git-revert 0.2.5 
autoclose-html 0.23.0 
autoupdate-packages 1.3.1 
busy-signal 1.4.3 
emmet 2.4.3 
file-icons 2.1.10 
intentions 1.1.5 
linter 2.2.0 
linter-htmlhint 1.3.3 
linter-jshint 3.1.5 
linter-mixed-indent 1.1.0 
linter-ui-default 1.6.4 
lucid-tabs 1.1.1 
minimap-plus 4.29.2 
open-recent 5.0.0 
pigments 0.40.2 
poseidon-syntax 0.3.0 
sass-autocompile 0.13.3 
scroll-through-time 0.2.0 
seti-ui 1.9.0 
todo-show 1.11.0 
```

**Comment by 50Wliu** [comment] 2017-08-11 03:00
Duplicate of #292.

**Closed by 50Wliu** 2017-08-11 03:00 UTC

**Comment by garethallenstringer** [comment] 2017-08-11 07:57
@50Wliu I have had both SCSS, and JS files wiped. That thread seems to pertain especially to JS files.

**Comment by 50Wliu** [comment] 2017-08-11 13:01
I double checked and #292 occurs when opening any file that has been deleted outside of Atom, not just JS files.
