### ISSUE TITLE
repeated uses of bracket-matcher:select-inside-brackets should match nested brackets

### ISSUE THREAD

**Issue by joachim-n** [atom/bracket-matcher#327] opened 2017-10-23 21:16 UTC
Given the following code:

```
function foo() {
  if (condition) {
    if (condition) {
      // Cursor here.
    }
  }
}
```

placing the cursor in the middle and issuing the bracket-matcher:select-inside-brackets command should successively select the pairs of brackets, expanding the selection each time.

Instead, it only selects the innermost set of brackets and doesn't select any further.

This is how it works on TextMate.

**Comment by rsese** [comment] 2017-10-24 04:42
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/bracket-matcher/issues/74. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-10-24 04:42 UTC
