### ISSUE TITLE
Feature request: Highlight brackets while the cursor is inside of them.

### ISSUE THREAD

**Issue by loggerhead** [atom/bracket-matcher#238] opened 2016-08-03 04:39 UTC
Quoted from https://discuss.atom.io/t/how-to-highlight-brackets-while-the-cursor-is-inside-of-them-not-just-right-next-to-them/22731:

> So Sublime Text has the feature where brackets will be highlighted / underlined not just when the cursor is on the same line, but also whilst in them.
> 
> ![](https://cdn-business.discourse.org/uploads/github_atom/original/3X/7/8/78480d54d18c55eac1829cff507b9e0e49563e5c.png)
> 
> But Atom only does this while the cursor is on the same line, right next to the bracket.
> 
> ![](https://cdn-business.discourse.org/uploads/github_atom/original/3X/6/3/63fa9a3ef9c729fb6abcc384c904d0ebc6e6693e.png)
> 
> Is there a setting to turn this on? Or is there a separate package that is required?

**Comment by 50Wliu** [comment] 2016-09-25 03:59
This is a duplicate of #57 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-09-25 03:59 UTC
