### ISSUE TITLE
Wrong HTML bracket matched when '>' is on separate line

### ISSUE THREAD

**Issue by bgschiller** [atom/bracket-matcher#340] opened 2018-01-24 19:43 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The wrong bracket is highlighted when the closing `>` is on a separate line. This is common in, for example, [Vue.js templates](https://trello-attachments.s3.amazonaws.com/58d428743111af1d0a20cf28/5a68e0e3a7dcd354167f55d2/317b1b0c4fc99ddc269ad253bb7a31ab/clip.txt).

![](https://trello-attachments.s3.amazonaws.com/58d428743111af1d0a20cf28/5a68e1b97b3c97493919ca8b/d398de8311c830b5c7f79e3be147480b/capture.png)

### Steps to Reproduce

1. Put the following into a buffer and set the grammar to 'HTML':

```
<div>
  <div
    id="something"
  >
  </div>
</div>
```

2. Put your cursor on the first div.

**Expected behavior:** 

The final closing `</div>` is underlined as matching.

**Actual behavior:**

The first `</div>` is underlined

**Reproduces how often:** [What percentage of the time does it reproduce?]
💯 

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

```
Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.11
git 2.11.0

bracket-matcher 0.88.0
```

**Comment by rsese** [comment] 2018-01-24 23:43
Thanks for the report!  This is a duplicate of https://github.com/atom/bracket-matcher/issues/333, and the fix will be in an upcoming release (I think the 1.25 releases).

**Closed by rsese** 2018-01-24 23:43 UTC
