### ISSUE TITLE
Highlight content between matching brackets when the cursor position is beside a bracket

### ISSUE THREAD

**Issue by multiwebinc** [atom/bracket-matcher#150] opened 2015-07-11 21:30 UTC
This is a feature I find useful from [Kate](http://kate-editor.org/) and I think would be useful in Atom too. When the cursor position is beside a bracket, it automatically highlights everything between there and the other matching bracket. This makes it easy to see where a code block ends. I find it useful when I have a large code block and I would like to quickly and easily see where it ends without actually selecting the text. If it only highlights the actual bracket instead of the whole code block it is more difficult to see.

Here's a screenshot of Kate: ![Screenshot][1]

  [1]: http://i.stack.imgur.com/VsbFP.png

**Comment by sdaitzman** [comment] 2015-07-12 17:46
:+1:

**Comment by sdaitzman** [comment] 2015-07-12 17:48
#30 seems the same to me

**Comment by 50Wliu** [comment] 2015-07-12 19:08
Thanks, @sdaitzman!  Closing this as a duplicate of #30.

**Closed by 50Wliu** 2015-07-12 19:08 UTC
