### ISSUE TITLE
nested brackets coloration

### ISSUE THREAD

**Issue by maxlevesque** [atom/bracket-matcher#84] opened 2014-11-21 09:33 UTC
Hi, First of all thanks for the very good job. You're amazing :).  
I would really like to see nested brackets to have different colors. For instance, outter brackets in black, inner in red, etc.

**Comment by WalterGR** [comment] 2016-01-17 23:25
Dupe of #170: "Rainbow"?

In any case, someone recently released a package that ostensibly does something similar: "My first package released (Coloured brackets)" - https://discuss.atom.io/t/my-first-package-released-coloured-brackets/21261.  I haven't tried it, but it might help.

**Comment by 50Wliu** [comment] 2016-01-18 00:17
Thanks @WalterGR - this seems similar enough to #170, so let's keep the conversation unified over there.

**Closed by 50Wliu** 2016-01-18 00:17 UTC
Labels: enhancement
