### ISSUE TITLE
Braces in strings are matched as if they are code.

### ISSUE THREAD

**Issue by Ceyaje** [atom/bracket-matcher#202] opened 2015-12-16 15:40 UTC
I do a lot of preprocessing utilities, so I have quite a few sections of code that look like this:

```
if (testString.indexOf("END") === -1) {
    testString = testString.slice(0,-1).trim();
    testString = testString + "END\n }";
};
```

Of course, the opening brace is being matched with the brace in the string instead of the actual brace. I'm rather upset because I really wanted to switch to Atom since it seems very well featured compared to Brackets, but I'll have to go back. I'm going to keep an eye on this issue though. I really hope it can be addressed.

**Comment by 50Wliu** [comment] 2015-12-16 16:39
This is a duplicate of #78 - please subscribe there for updates.

**Closed by 50Wliu** 2015-12-16 16:39 UTC
