### ISSUE TITLE
bracket-matcher highlight in comments and quotes

### ISSUE THREAD

**Issue by heck82** [atom/bracket-matcher#235] opened 2016-06-09 16:12 UTC
Atom nice editor, and i hope with common efforts it become better.
Issue: 
bracket-matcher highlight brackets in comments and quotes, and it a little bit annoying.
thanks to all who trying resolve this issue.

**Comment by 50Wliu** [comment] 2016-06-09 20:06
This is a duplicate of #78 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-06-09 20:06 UTC
