### ISSUE TITLE
Uncaught Error: This TextEditor has been destroyed

### ISSUE THREAD

**Issue by aknuds1** [atom/bracket-matcher#178] opened 2015-09-11 17:48 UTC
Not sure how to reproduce.

**Atom Version**: 1.0.11
**System**: Mac OS X 10.9.5
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package, v0.76.0

### Stack Trace

Uncaught Error: This TextEditor has been destroyed

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1097

Error: This TextEditor has been destroyed
  at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1097:15)
  at Marker.module.exports.Marker.getHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:179:33)
  at Cursor.module.exports.Cursor.getScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:90:26)
  at TextEditor.module.exports.TextEditor.getCursorScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1371:35)
  at TextEditor.module.exports.TextEditor.isFoldedAtCursorRow (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2559:44)
  at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher-view.js:111:23)
  at new BracketMatcherView (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher-view.js:74:12)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/main.js:30:9
  at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:281:16
  at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:342:18
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:352:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:339:26
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:345:20)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:313:14)
  at Object.module.exports.next (/Users/arve/.atom/packages/ctrl-last-tab/lib/ctrl-last-tab.coffee:60:10)
  at atom-workspace.subscriptions.add.atom.commands.add.ctrl-last-tab:next (/Users/arve/.atom/packages/ctrl-last-tab/lib/ctrl-last-tab.coffee:25:10)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
  4x -1:43 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -1:41.9.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:41.7.0 refactor:done (atom-text-editor.editor.is-focused)
     -1:41.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:39.6.0 core:save (atom-text-editor.editor.is-focused)
  2x -1:37.2.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:12.7.0 find-and-replace:show (atom-text-editor.editor.is-focused)
  3x -1:10.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:08.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:06.6.0 find-and-replace:find-next (atom-text-editor.editor.mini.is-focused)
     -0:31.5.0 ctrl-last-tab:previous (atom-text-editor.editor.is-focused)
     -0:24.3.0 ctrl-last-tab:next (ul.list-inline.tab-bar.inset-panel)
     -0:21 core:close (atom-text-editor.editor.is-focused)
 15x -0:18.3.0 ctrl-last-tab:next (atom-text-editor.editor.is-focused)
     -0:03.1.0 core:close (atom-text-editor.editor.is-focused)
  7x -0:02.4.0 ctrl-last-tab:next (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "linter-flake8"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v1.2.1
auto-reveal-in-sidebar, v0.5.0
coffee-refactor, v0.7.0
ctrl-last-tab, v0.2.0
editor-settings, v1.0.4
editorconfig, v1.2.0
language-clojure, v0.16.0
language-docker, v1.1.3
language-gradle, v0.0.3
language-groovy, v0.4.0
language-haskell, v1.4.3
language-jade, v0.6.2
language-nginx, v0.5.5
language-scala, v1.1.3
linter, v1.5.1
linter-eslint, v3.0.2
linter-jsonlint, v1.0.1
linter-shellcheck, v1.0.1
package-cop, v0.2.10
pretty-json, v0.4.1
refactor, v0.6.0
tabs-to-spaces, v0.11.1

# Dev
No dev packages
```

**Comment by slikts** [comment] 2015-09-21 12:25
It's because of ctrl-last-tab.

Reproduce: Open 2 tabs, press Ctrl-Tab, then Ctrl-Shift-Tab and the error happens.

**Comment by izuzak** [comment] 2015-09-22 07:42
Thanks for the help in reproducing this, @slikts -- I was able to trigger this exception using your steps with the ctrl-last-tab package. 

@nathansobo wondering if you have any thoughts about this? Is this something we should guard against somehow or make sure it gets blamed on a different package?

**Comment by nathansobo** [comment] 2015-09-22 13:40
I'm still having trouble reproducing this on master with the latest ctrl-last-tab package.

**Comment by nathansobo** [comment] 2015-09-22 13:44
Okay, I was able to cause it after closing one of the tabs... investigating.

**Comment by nathansobo** [comment] 2015-09-22 13:52
That package is adding destroyed pane items... check out my PR that guards against that happening by throwing an exception immediately.

**Closed** 2015-09-22 16:57 UTC
Labels: needs-reproduction, uncaught-exception
