### ISSUE TITLE
Parentheses not autocompleted after backslash

### ISSUE THREAD

**Issue by jiyinyiyong** [atom/bracket-matcher#198] opened 2015-12-10 15:21 UTC
This case appear to be very rough to me and open parenthesis is not correctly closed after a `\`

```coffee
    hasEscapeSequenceBeforeCursor = previousCharacters.match(/\\/g)?.length >= 1 # To guard against the "\\" sequence

    if text is '#' and @isCursorOnInterpolatedString()
      autoCompleteOpeningBracket = atom.config.get('bracket-matcher.autocompleteBrackets') and not hasEscapeSequenceBeforeCursor
      text += '{'
      pair = '}'
    else
      autoCompleteOpeningBracket = atom.config.get('bracket-matcher.autocompleteBrackets') and @isOpeningBracket(text) and not hasWordAfterCursor and not (@isQuote(text) and (hasWordBeforeCursor or hasQuoteBeforeCursor)) and not hasEscapeSequenceBeforeCursor
      pair = @pairedCharacters[text]
```
https://github.com/atom/bracket-matcher/blob/master/lib/bracket-matcher.coffee#L63

It appear to be very annoying to me, can you make it smarter? How about using `/\\$/` instead of `/\\/g`?

**Comment by 50Wliu** [comment] 2016-09-25 03:23
This is a duplicate of #80 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-09-25 03:23 UTC
