### ISSUE TITLE
At Cannot read property 'openScopes' of undefined

### ISSUE THREAD

**Issue by vivirishe** [atom/bracket-matcher#307] opened 2017-08-11 00:29 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package 0.86.0

### Stack Trace

Failed to activate the bracket-matcher package

```
At Cannot read property 'openScopes' of undefined

TypeError: Cannot read property 'openScopes' of undefined
    at TagFinder.module.exports.TagFinder.scopesForPositionMatchRegex (/Users/Viviana/Downloads/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/tag-finder.js:55:28)
    at TagFinder.module.exports.TagFinder.isCursorOnTag (/Users/Viviana/Downloads/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/tag-finder.js:45:25)
    at TagFinder.module.exports.TagFinder.findMatchingTags (/Users/Viviana/Downloads/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/tag-finder.js:174:22)
    at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (/Users/Viviana/Downloads/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:128:41)
    at BracketMatcherView.updateMatch (/Users/Viviana/Downloads/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:3:65)
    at new BracketMatcherView (/Users/Viviana/Downloads/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:92:18)
    at /Users/Viviana/Downloads/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/main.js:16:15
    at Workspace.observeTextEditors (/Users/Viviana/Downloads/Atom.app/Contents/Resources/app/src/workspace.js:717:15)
    at Object.activate (/Users/Viviana/Downloads/Atom.app/Contents/Resources/app/node_modules/bracket-matcher/lib/main.js:12:35)
    at Package.module.exports.Package.activateNow (/Users/Viviana/Downloads/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Users/Viviana/Downloads/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Users/Viviana/Downloads/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Users/Viviana/Downloads/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Users/Viviana/Downloads/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Users/Viviana/Downloads/Atom.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /Users/Viviana/Downloads/Atom.app/Contents/Resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (/Users/Viviana/Downloads/Atom.app/Contents/Resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (/Users/Viviana/Downloads/Atom.app/Contents/Resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (/Users/Viviana/Downloads/Atom.app/Contents/Resources/app/src/package-manager.js:603:52)
    at /Users/Viviana/Downloads/Atom.app/Contents/Resources/app/src/atom-environment.js:843:36
```

### Commands

```
  3x -2:33.5.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
autosave-plus 0.6.0 
color-picker 2.2.5 
emmet 2.4.3 
erb-helper 1.1.0 
highlight-selected 0.13.1 
minimap 4.29.6 
open-in-browsers 0.0.30 
open-recent 5.0.0 
pigments 0.40.2 
react 0.16.2 
seti-ui 1.9.0 
Sublime-Style-Column-Selection 1.7.4 
tree-ignore 0.6.2 
white-cursor 0.7.0 
```

**Comment by 50Wliu** [comment] 2017-08-11 03:00
Duplicate of #292.

**Closed by 50Wliu** 2017-08-11 03:00 UTC
