### ISSUE TITLE
(Bug) Bracket matching for multi-line <article> tag

### ISSUE THREAD

**Issue by rickydam** [atom/bracket-matcher#287] opened 2017-05-08 13:55 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
The bracket matching for a multi-line article tag has a bug.

### Steps to Reproduce
1. Make a blank PHP file
2. Paste in the code below.
(NOTE: If you add a space after article in the code "<article " like that, the problem will not occur.)

#### How I found it
```
<article
  id="post-<?php the_ID(); ?>"
  <?php if(is_category('featured')): ?> class="featured-post" <?php endif; ?>>
  
</article>
```

#### Simply this can reproduce it too
```
<article
>
</article>
```
<img src="http://i.imgur.com/PMBA0U9.png">

**Expected behavior:**
When the text cursor is on the closing article tag, the matching line should stop the same way it does when you have the text cursor on the opening article tag. as shown below.
<img src="http://i.imgur.com/S8iip84.png">

**Actual behavior:**
Instead, this is what you see when the text cursor is on the closing article tag.
<img src="http://i.imgur.com/bBoWz1d.png">

**Reproduces how often:**
100%

### Versions
Atom (1.16.0)
bracket-matcher (0.85.3)
OS X El Capitan (10.11.6)

**Comment by rsese** [comment] 2017-05-09 19:38
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/bracket-matcher/issues/208. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-05-09 19:38 UTC
