### ISSUE TITLE
Matched tag underlines fill screen with multiline attributes.

### ISSUE THREAD

**Issue by phyllisstein** [atom/bracket-matcher#244] opened 2016-09-04 22:21 UTC
Hey there! I just noticed that in both Atom mainline and Atom beta, tags with their attributes on multiple lines cause `bracket-matcher` to choke a little:

<img width="1440" alt="screen shot" src="https://cloud.githubusercontent.com/assets/2207980/18234251/40c71728-72cc-11e6-9a24-0587b7270d76.png">

I would have expected it to detect the end of line after the first `video` tag and stop underlining at that point on the screen; instead, lacking a closing `>` character, the underline continues to the screen edge.

**ETA:** This appears to _only_ happen when the cursor is positioned at the closing tag:

![screenflow](https://cloud.githubusercontent.com/assets/2207980/18234279/f5a59516-72cc-11e6-89dd-e1e7e94b09e5.gif)

**Comment by 50Wliu** [comment] 2016-09-04 23:15
Does this happen with all syntax themes, or just one-dark?

**Comment by phyllisstein** [comment] 2016-09-04 23:57
Seems to happen in all of them I’ve tried, including One Light...

<img width="1440" alt="screen shot 1" src="https://cloud.githubusercontent.com/assets/2207980/18234631/b0a5746a-72d9-11e6-87a5-d4eb2fe30f29.png">

...Fizzy...

<img width="1440" alt="screen shot 2" src="https://cloud.githubusercontent.com/assets/2207980/18234633/b6d919a4-72d9-11e6-8c14-42f181d56f6b.png”>

...and Octocat.

<img width="1440" alt="screen shot 3" src="https://cloud.githubusercontent.com/assets/2207980/18234636/bf5d0ec8-72d9-11e6-9559-86e6e5e2fcee.png">

**Comment by 50Wliu** [comment] 2016-09-25 03:20
This is a duplicate of #208 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-09-25 03:20 UTC
Labels: bug
