### ISSUE TITLE
'ctrl-m' on Mac waits for very long before moving to the matching bracket

### ISSUE THREAD

**Issue by baipenghan** [atom/bracket-matcher#122] opened 2015-04-01 08:44 UTC
'ctr-m' on Mac waits for very long before moving to the matching bracket

**Comment by brunetton** [comment] 2015-04-21 13:57
Have a look to your keybinding-resolver (https://atom.io/packages/keybinding-resolver) to make sure the sortcut is not used by another package (I would bet on merge-conflicts: https://atom.io/packages/merge-conflicts that also use `ctrl-m`)

**Comment by lee-dohm** [comment] 2015-04-21 14:52
I agree with @brunetton, this is probably a key binding conflict. I am unable to reproduce the issue you mention @baipenghan using Atom v0.193.0-af5618e on Mac OS X 10.10.3.

Please let us know if there is any other information we can provide.

**Comment by baipenghan** [comment] 2015-04-21 15:48
Yes, it's a key-bindings conflicts with merge-conflicts. And I deleted the keybinding shortcuts in merge-conflicts keymap file. Is this the best way to resolve it?

**Comment by lee-dohm** [comment] 2015-04-22 04:35
Well, if you changed the keymap file in the package itself, it will probably be overwritten on the next update. You should put your keymap modifications in your `~/.atom/keymap.cson`. It can be opened in Atom from the Atom menu on OS X.

**Comment by kevinsawicki** [comment] 2015-07-29 17:20
Closing this out since it seems to be a keybinding conflict issue and not something fixable in the bracket-matcher package.

**Closed by kevinsawicki** 2015-07-29 17:20 UTC
Labels: more-information-needed, needs-reproduction
