### ISSUE TITLE
selection extends to HTML tag bug

### ISSUE THREAD

**Issue by PierBover** [atom/bracket-matcher#188] opened 2015-11-16 16:42 UTC
Most of the time when using `ctrl + cmd + m` the selection expands to the text inside the HTML tag. But there are times when it includes some of the attributes of the HTML tag, which is undesired.

Here is an example:
![image](https://cloud.githubusercontent.com/assets/226483/11188024/8953e346-8c4e-11e5-9cb8-2ae4b0289008.png)

I'm on latest public release (0.79.0)

**Comment by izuzak** [comment] 2015-11-16 16:45
Thanks for the report, @PierBover. I think this is a duplicate of https://github.com/atom/bracket-matcher/issues/117 so I'm closing this in favor of that issue. Let me know if I misunderstood, though!

**Closed by izuzak** 2015-11-16 16:45 UTC

**Comment by PierBover** [comment] 2015-11-16 16:50
Thanks @izuzak. Yes, it seems to be the same issue.

Is anyone working on this? It seems it was reported 6 months ago.

**Comment by izuzak** [comment] 2015-11-16 16:51
> Is anyone working on this? It seems it was reported 6 months ago.

I'm not aware of anyone working on it. If you'd like to work on it -- please feel free to do so and submit a pull request.
