### ISSUE TITLE
Weirdness surrounding selection with braces when inside parens

### ISSUE THREAD

**Issue by nathansobo** [atom/bracket-matcher#67] opened 2014-08-27 21:52 UTC
![surround](https://cloud.githubusercontent.com/assets/1789/4068035/674c4d84-2e34-11e4-9bce-2ef00b364dde.gif)

**Comment by izuzak** [comment] 2015-09-15 13:13
Closing this since we were unable to reproduce (I just tried now and failed), and there haven't been any new reports about this for over a year.

**Closed by izuzak** 2015-09-15 13:13 UTC
Labels: bug
