### ISSUE TITLE
Ignore matching bracket if it is commented out

### ISSUE THREAD

**Issue by nlangle** [atom/bracket-matcher#146] opened 2015-06-25 23:49 UTC
Consider ignoring commented out bracket matches.  For example:
//Refresh Results
      function reFresh() {
      //Get new showVals
        showVals = [];
        $('#filter input:checked').each(function(){
          if ($(this).val() != '' && $(this).val() != undefined){
            showVals.push($(this).val());
          }
        });
        //Some other functions go here...
        //And if there is some commented out code, like the following line
        //setTimeout(function() {
        //but we are no longer using the timeout function above, the next bracket will think its match is the curly bracket after the commented out timeout function instead of the curly bracket after function reFresh()
      };

However, just by placing the cursor at the closing curly bracket, the match will not be highlighted.  Cntrl+M will jump to the commented out bracket.  Placing the cursor at the opening curly bracket after reFresh() will not find a match.

**Comment by izuzak** [comment] 2015-06-26 11:56
Thanks for the report -- I believe this is a duplicate of https://github.com/atom/bracket-matcher/issues/78.

**Closed by izuzak** 2015-06-26 11:56 UTC
