### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getBufferPosition' of undefined

### ISSUE THREAD

**Issue by benogle** [atom/bracket-matcher#89] opened 2014-12-11 17:01 UTC
_From @fbrundu on December 11, 2014 13:58_

Uncaught TypeError: Cannot read property 'getBufferPosition' of undefined

**Atom Version**: 0.154.0
**System**: linux 3.13.0-41-generic
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package

### Steps To Reproduce

I don't know exactly how to reproduce it but it happens when I press Tab at the beginning of the line. Afterwards, it can be reproduced pressing any key. I am using also the `vim-mode` package, I don't know if it is related.

### Stack Trace

```
At /opt/atom/resources/app/node_modules/text-buffer/lib/history.js:124

TypeError: Cannot read property 'getBufferPosition' of undefined
  at TextEditor.module.exports.TextEditor.getCursorBufferPosition (/opt/atom/resources/app/src/text-editor.js:1300:34)
  at BracketMatcher.module.exports.BracketMatcher.insertText (/opt/atom/resources/app/node_modules/bracket-matcher/lib/bracket-matcher.js:82:42)
  at TextEditor.<anonymous> (/opt/atom/resources/app/node_modules/bracket-matcher/lib/bracket-matcher.js:3:61)
  at TextEditor.object.(anonymous function) [as insertText] (/opt/atom/resources/app/node_modules/underscore-plus/lib/underscore-plus.js:69:20)
  at /opt/atom/resources/app/src/text-editor-component.js:653:23
  at History.module.exports.History.transact (/opt/atom/resources/app/node_modules/text-buffer/lib/history.js:115:18)
  at TextBuffer.module.exports.TextBuffer.transact (/opt/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:683:27)
  at TextEditor.module.exports.TextEditor.transact (/opt/atom/resources/app/src/text-editor.js:1146:26)
  at [object Object].module.exports.React.createClass.onTextInput (/opt/atom/resources/app/src/text-editor-component.js:652:30)
  at HTMLDivElement.boundMethod (/opt/atom/resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1295:21)

```

_Copied from original issue: atom/atom#4546_

**Comment by mattberkowitz** [comment] 2015-01-23 15:55
A user of my plugin, autoclose-html, reported getting this error after upgrading to the latest version (https://github.com/mattberkowitz/autoclose-html/issues/46). I don't think it's specifically related to autoclose-html, just the insertText triggering the _.adviseBefore of bracket-matcher's insertText. Perhaps the upgrade (installation?) of a plugin is causing bracket-matcher to lose it's editor reference?

**Comment by phammer** [comment] 2015-01-24 19:00
Issue also started showing up since yesterday. I disabled the bracket-matcher for now.

**Comment by staticinteger** [comment] 2015-01-24 19:40
Also getting this issue as of today... Unfortunate, this increases my workflow greatly. Hopefully it gets fixed soon!

**Comment by JamesGould123** [comment] 2015-02-03 05:33
I am getting this error as well, whenever I type `<div class="clear` then hit the right arrow to exit the auto-completed `"`. It errors when I hit `>`. I am also using the autoclose-html package, and it shows in my stack trace:

<pre>
TypeError: Cannot read property 'getBufferPosition' of undefined
  at TextEditor.module.exports.TextEditor.getCursorBufferPosition (c:\Users\James\AppData\Local\atom\app-0.176.0\resources\app\src\text-editor.js:1339:34)
  at BracketMatcher.module.exports.BracketMatcher.insertText (c:\Users\James\AppData\Local\atom\app-0.176.0\resources\app\node_modules\bracket-matcher\lib\bracket-matcher.js:82:42)
  at TextEditor.<anonymous> (c:\Users\James\AppData\Local\atom\app-0.176.0\resources\app\node_modules\bracket-matcher\lib\bracket-matcher.js:3:61)
  at TextEditor.object.(anonymous function) [as insertText] (c:\Users\James\AppData\Local\atom\app-0.176.0\resources\app\node_modules\underscore-plus\lib\underscore-plus.js:76:20)
  at c:\Users\James\.atom\packages\autoclose-html\lib\autoclose-html.coffee:96:24
</pre>

I am using version 0.176.0 of atom on Windows 7.

**Comment by JamesGould123** [comment] 2015-02-03 19:01
We may want to transfer this issue over to the atom core repository, as the problem appears to originate in the TextEditor > https://github.com/atom/atom/blob/master/src/text-editor.coffee

**Comment by Eiamnacken** [comment] 2015-03-19 08:29
Got the same error OS Opensuse 13.2. I also use autoclose-html. I appears when it type the following <code>form action="http://localhost:8080/forms/stapelsuche.php" method="get"</code>

This is what i get fom the error 
<code>[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0-f9aedb7
**System**: linux 3.16.7-7-desktop
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package, v0.71.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getBufferPosition' of undefined

```
At /usr/local/share/atom/resources/app/src/text-editor.js:1378

TypeError: Cannot read property 'getBufferPosition' of undefined
  at TextEditor.module.exports.TextEditor.getCursorBufferPosition (/usr/local/share/atom/resources/app/src/text-editor.js:1378:34)
  at BracketMatcher.module.exports.BracketMatcher.insertNewline (/usr/local/share/atom/resources/app/node_modules/bracket-matcher/lib/bracket-matcher.js:133:42)
  at TextEditor.<anonymous> (/usr/local/share/atom/resources/app/node_modules/bracket-matcher/lib/bracket-matcher.js:3:61)
  at TextEditor.object.(anonymous function) [as insertNewline] (/usr/local/share/atom/resources/app/node_modules/underscore-plus/lib/underscore-plus.js:76:20)
  at /home/eiamnacken/.atom/packages/autoclose-html/lib/autoclose-html.coffee:94:28

```

### Commands

```
  2x -2:20.8 core:move-right (atom-text-editor.editor.is-focused)
     -2:02.7 core:move-left (atom-text-editor.editor.is-focused)
  4x -2:01.9 core:move-right (atom-text-editor.editor.is-focused)
     -1:59.3 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
  3x -1:58.4 core:move-right (atom-text-editor.editor.is-focused)
     -1:52.2 core:save (atom-text-editor.editor.is-focused)
 48x -1:50.9 core:move-right (atom-text-editor.editor.is-focused)
     -0:56.1 core:copy (atom-text-editor.editor.is-focused)
     -0:55.9 core:backspace (atom-text-editor.editor.is-focused)
 45x -0:55.1 core:move-down (atom-text-editor.editor.is-focused)
  3x -0:52.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:50.5 editor:newline (atom-text-editor.editor.is-focused)
     -0:48.7 core:paste (atom-text-editor.editor.is-focused)
  3x -0:47.1 core:save (atom-text-editor.editor.is-focused)
  5x -0:03.9 core:move-down (atom-text-editor.editor.is-focused)
     -0:02.4 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.3
autoclose-html, v0.15.0
autocomplete-html, v0.5.0
color-picker, v1.4.4
linter, v0.12.0
linter-csslint, v0.0.11
linter-htmlhint, v0.0.8
linter-jscs, v1.9.0
monokai, v0.12.0
seti-ui, v0.6.3

# Dev
No dev packages
```

</code>

**Comment by eviljoe** [comment] 2015-03-23 11:25
I was able to reproduce this consistently, but it is a bit of a... process...
 1. Open any HTML document (H<sub>1</sub>)
 1. Open up a split pane (`ctrl+k, down` is what I have been using to reproduce this)
 1. In the newly opened split pane open a *different* HTML document (H<sub>2</sub>)
 1. In H<sub>1</sub>, type an element name that will cause the autoclose-html package to autoclose an HTML element name (e.g. "&lt;div&gt;").

When I do this, the exception is thrown every time autoclose-html does its thing.

**Comment by aftermathew** [comment] 2015-05-08 13:42
This issue is getting thrown reliably for me using the [markdown-toc](https://atom.io/packages/markdown-toc) package.

Essentially the package works great in the first file I use it in after opening atom.  After that, if I try and use it in any other buffer, command keeps generating extra TOCs in the first buffer I was in.

If I close the first buffer this error is thrown.

I need to quit Atom entirely to make the package work with a different buffer.

**Comment by bartlomiejwolk** [comment] 2015-07-22 15:38
I have exactly the same problem as aftermathew. I'm using _Atom_ 1.0.2 and _markdown-toc_ 0.3.0.

**Comment by jeremythings** [comment] 2015-07-23 14:49
I am having same problem, Atom 1.0.0 and markdown-toc 0.3.0 on Linux Mint 17

**Comment by adamgall** [comment] 2015-08-12 15:52
+1 with Atom 1.0.5 and markdown-toc 0.3.0

**Comment by 50Wliu** [comment] 2016-09-25 03:45
No further reports, closing.

**Closed by 50Wliu** 2016-09-25 03:45 UTC
Labels: bug, uncaught-exception
