### ISSUE TITLE
Uncaught Error: This TextEditor has been destroyed

### ISSUE THREAD

**Issue by mrmckeb** [atom/bracket-matcher#228] opened 2016-04-27 04:57 UTC
To be honest, I'm not sure why I'm seeing this error. It happens whenever I tried to type into the editor. When I closed the pane and re-opened the file, it was fine - but none of my changes were there.

**Atom Version**: 1.7.2
**System**: Mac OS X 10.10.5
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package, v0.81.0
### Stack Trace

Uncaught Error: This TextEditor has been destroyed

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:1002

Error: This TextEditor has been destroyed
    at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:794:15)
    at TextEditorMarker.module.exports.TextEditorMarker.getHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker.js:179:33)
    at Cursor.module.exports.Cursor.getScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:73:26)
    at TextEditor.module.exports.TextEditor.getCursorScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1490:35)
    at TextEditor.module.exports.TextEditor.isFoldedAtCursorRow (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2697:44)
    at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher-view.js:130:23)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher-view.js:43:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeTextEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1344:20)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:854:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/whitespace/lib/whitespace.js:52:25
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1082:20)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1074:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:660:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:718:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:701:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:684:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:214:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -1:03.0 core:save (atom-text-editor.editor.is-focused)
  2x -1:01.6.0 core:undo (atom-text-editor.editor.is-focused)
 13x -0:49.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:36.6.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:34.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:33.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:18.8.0 editor:newline (atom-text-editor.editor.is-focused)
  7x -0:18 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:16 core:save (atom-text-editor.editor.is-focused)
     -0:13.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:13.3.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:12.8.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:12.8.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:12.8.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:10.4.0 core:backspace (atom-text-editor.editor.is-focused)
  9x -0:10 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "destroyEmptyPanes": false,
    "openEmptyEditorOnStart": false
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.29.7
atom-ternjs, v0.14.1
autoclose-html, v0.23.0
clock, v1.7.0
feedback, v0.38.0
language-dustjs, v0.2.0
language-ejs, v0.2.0
linter, v1.11.4
linter-csslint, v1.3.2
linter-jscs, v3.5.0
linter-jshint, v2.1.0
linter-php, v1.2.0
linter-scss-lint, v2.5.1
merge-conflicts, v1.4.2
minimap, v4.23.1
minimap-bookmarks, v0.3.0
minimap-find-and-replace, v4.5.1
minimap-git-diff, v4.3.0
minimap-linter, v1.1.1
minimap-pigments, v0.2.0
minimap-selection, v4.4.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-04-27 14:17
@mrmckeb Can you reproduce this consistently?  If so can you try safe mode (`atom --safe`)?

**Comment by mrmckeb** [comment] 2016-04-27 23:32
@50Wliu I can't sorry, I managed to get it to show up a moment ago again, and saw it several times yesterday. Once it starts, it happens every time I close a file, and a restart of Atom resolves the issue.

When it last happened I tried following the same steps I'd just completed, and that didn't seem to cause the same issue. So replication might be tricky.

I'll keep an eye on it and update you immediately if I find a possible cause.

**Comment by 50Wliu** [comment] 2016-09-25 03:14
No further reports, so closing.

**Comment by Chinney** [comment] 2016-10-25 10:44
Further report right here. Updated a few packages yesterday. Having this problem since then.

**Comment by timrichd** [comment] 2016-11-28 13:43
Also having this issue

**Comment by timrichd** [comment] 2016-11-29 10:32
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Ubuntu 16.04.1
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package, v0.81.0


### Stack Trace

Uncaught Error: This TextEditor has been destroyed

```
At /usr/share/atom/resources/app.asar/src/pane.js:1002

Error: This TextEditor has been destroyed
    at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/usr/share/atom/resources/app.asar/src/display-buffer.js:794:15)
    at TextEditorMarker.module.exports.TextEditorMarker.getHeadScreenPosition (/usr/share/atom/resources/app.asar/src/text-editor-marker.js:179:33)
    at Cursor.module.exports.Cursor.getScreenPosition (/usr/share/atom/resources/app.asar/src/cursor.js:73:26)
    at TextEditor.module.exports.TextEditor.getCursorScreenPosition (/usr/share/atom/resources/app.asar/src/text-editor.js:1490:35)
    at TextEditor.module.exports.TextEditor.isFoldedAtCursorRow (/usr/share/atom/resources/app.asar/src/text-editor.js:2697:44)
    at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (/usr/share/atom/resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher-view.js:130:23)
    at /usr/share/atom/resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher-view.js:43:26
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeTextEvent (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1344:20)
    at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:854:14)
    at /usr/share/atom/resources/app.asar/node_modules/whitespace/lib/whitespace.js:52:25
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1082:20)
    at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1074:19)
    at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:660:26)
    at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app.asar/src/pane.js:718:18)
    at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:701:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:684:35)
    at atom-workspace.commandRegistry.add.core:save (/usr/share/atom/resources/app.asar/src/register-default-commands.js:214:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -3:46 pane:split-right-and-copy-active-item (atom-text-editor.editor.is-focused)
     -0:05.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:01.4.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.13
fonts, v1.7.0
js-hyperclick, v1.9.0
language-docker, v1.1.7
language-perl, v0.37.0
language-perl-template-toolkit, v0.1.0
letter-spacing, v0.3.1
line-diff-details, v1.4.0
linter, v1.11.18
linter-eslint, v7.2.3
linter-perl, v0.8.0
linter-perlcritic, v1.2.3
linter-stylelint, v3.6.0
minimap, v4.25.6
minimap-git-diff, v4.3.1
minimap-highlight-selected, v4.4.0
minimap-linter, v1.6.0
monokai, v0.18.0
perltidy, v3.0.0
pretty-json, v1.6.1
react, v0.16.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2016-11-29 15:52
@Chinney what Atom version are you using?
@timrichd The latest version of Atom is currently 1.12.6.  Please update and see if you can still reproduce this.

**Comment by roccomuso** [comment] 2017-03-16 11:22
Same issue!

**Comment by Chinney** [comment] 2017-12-02 12:00
Sorry for the late response. I am currently on 1.8.0. Can't reproduce the issue anymore.

**Comment by 50Wliu** [comment] 2017-12-04 19:02
@Chinney thanks for the update.  You might want to upgrade Atom as the latest version is Atom 1.22.1.  I'll be closing this issue since bracket-matcher has undergone substantial changes since the last report.

**Closed by 50Wliu** 2017-12-04 19:02 UTC
Labels: more-information-needed, needs-reproduction, uncaught-exception
