### ISSUE TITLE
Highlighting feature request

### ISSUE THREAD

**Issue by andersennl** [atom/bracket-matcher#47] opened 2014-06-26 08:40 UTC
First of all, thanks a lot for this really useful package. While using it for some time now, I've noticed that it would be nice to not only see a underline marking the matching bracket, but a "block hightlight", surrounding the whole bracket in a maybe yellowish color would be  more noticeable. 

Would it be possible to add some kind of switch in the package setings to switch between these two display types? Thanks again!

**Comment by 50Wliu** [comment] 2016-09-25 03:54
This is a duplicate of #30 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-09-25 03:54 UTC
Labels: enhancement
