### ISSUE TITLE
Feature Request: extend select-inside-brackets

### ISSUE THREAD

**Issue by cortner** [atom/bracket-matcher#239] opened 2016-08-10 17:49 UTC
It would be really convenient, if I have nested brackets, e.g., 
```
  (some text and (some more text) and more)
```
that if I hit `select-inside-brackets` once when I am in the inner bracket then the inner bracket is selected, but if I hit it twice, then the outer bracket is selected.

**Comment by 50Wliu** [comment] 2016-08-10 18:56
This is a duplicate of #74 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-08-10 18:56 UTC

**Comment by cortner** [comment] 2016-08-11 02:03
Apologies
