### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isEmpty' of undefined

### ISSUE THREAD

**Issue by kayone** [atom/bracket-matcher#173] opened 2015-08-27 17:28 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.5
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package, v0.76.0

### Stack Trace

Uncaught TypeError: Cannot read property 'isEmpty' of undefined

```
At /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:760

TypeError: Cannot read property 'isEmpty' of undefined
  at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher-view.js:108:42)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/bracket-matcher/lib/bracket-matcher-view.js:40:24
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/text-editor.js:236:32
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at DisplayBuffer.module.exports.DisplayBuffer.emitDidChange (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:313:20)
  at DisplayBuffer.module.exports.DisplayBuffer.updateScreenLines (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1595:19)
  at DisplayBuffer.module.exports.DisplayBuffer.handleTokenizedBufferChange (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1554:12)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:5:61
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TokenizedBuffer.module.exports.TokenizedBuffer.handleBufferChange (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:404:27)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:64:24
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyChange (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:635:20)
  at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:789:16)
  at TextBuffer.module.exports.TextBuffer.transact (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:758:14)
  at TextEditor.module.exports.TextEditor.transact (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1155:26)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/text-editor.js:776:24
  at TextEditor.module.exports.TextEditor.mergeSelections (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2019:43)
  at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1993:35)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/text-editor.js:774:19)
  at TextEditor.module.exports.TextEditor.backspace (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/text-editor.js:765:19)
  at TextEditor.object.(anonymous function) [as backspace] (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
  at TextEditor.atom.commands.add.stopEventPropagationAndGroupUndo.core:backspace (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:452:19)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:320:34
  at TextBuffer.module.exports.TextBuffer.transact (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:755:18)
  at TextEditor.module.exports.TextEditor.transact (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1155:26)
  at atom-text-editor.newCommandListeners.(anonymous function) (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:319:22)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
 11x -1:43.9.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
     -1:02.6.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
     -1:02.4.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:59.1.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
  2x -0:39.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:38.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:37.8.0 core:cut (atom-text-editor.editor.is-focused)
  2x -0:36 core:move-up (atom-text-editor.editor.is-focused)
     -0:35.5.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:34.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:32.1.0 core:cut (atom-text-editor.editor.is-focused)
     -0:32 core:save (atom-text-editor.editor.is-focused)
     -0:19.6.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
  3x -0:16.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:07.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:06.5.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-objective-c",
      "language-c",
      "language-clojure",
      "language-java",
      "language-php",
      "welcome",
      "atom-ctags",
      "auto-indent",
      "git-control",
      "wrap-guide",
      "clipboard-plus",
      "autoflow",
      "autosave",
      "background-tips",
      "toolbar-basic",
      "symbols-tree-view",
      "seti-icons",
      "linter-less",
      "omnisharp-atom"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.11
atom-handlebars, v1.1.0
atom-ternjs, v0.7.2
atom-yeoman, v0.3.13
auto-reveal-in-sidebar, v0.5.0
autocomplete-paths, v1.0.2
clipboard-history, v0.6.6
color-picker, v2.0.11
file-icons, v1.6.9
file-types, v0.5.1
flex-tool-bar, v0.5.0
highlight-selected, v0.10.1
json-schema, v0.1.11
language-diff, v0.3.1
linter, v1.4.3
linter-jscs, v2.0.4
linter-jshint, v1.1.5
local-history, v3.2.3
minimap, v4.13.2
minimap-find-and-replace, v4.3.0
minimap-git-diff, v4.1.8
minimap-hide, v0.3.0
minimap-highlight-selected, v4.3.0
pigments, v0.11.0
project-manager, v1.16.0
recent-files-fuzzy-finder, v0.1.4
sync-settings, v0.6.0
tool-bar, v0.1.8
underscorejs-snippets, v0.2.2
zentabs, v0.8.6

# Dev
No dev packages
```

**Comment by radicaled** [comment] 2015-10-01 21:38
I have a file I can't edit in Atom because of this -- and temporarily disabling the package doesn't seem to remove whatever event listeners there are that trigger this, so it means I have to disable this package, restart Atom, and only then can I edit this file.

**Comment by izuzak** [comment] 2015-10-02 21:17
@radicaled Can you share that file so that we can try and reproduce the problem? And just to make sure,  are you able to reproduce this problem in Atom 1.0.19 in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

**Comment by radicaled** [comment] 2015-10-02 22:16
https://gist.github.com/radicaled/e130e4624fbe58cdbfcf

Frustratingly enough, I'm now unable to reproduce this problem anymore. After I finished working on the files (I was editing the above file in vim), I closed all my tabs and restarted Atom, and then... poof, no more error. The version of the file in the gist is pretty close to the original state when the error occurred. Hope it still helps.

**Comment by izuzak** [comment] 2015-10-03 06:47
Thanks, @radicaled. Unfortunately, I'm unable to reproduce the problem with that file as well. If you manage to reproduce this again, we'd appreciate if you could post the version which is causing problems.

**Comment by izuzak** [comment] 2015-10-03 06:57
@radicaled And just to double-check something -- which version of Atom were you using when you noticed this exception?

**Comment by radicaled** [comment] 2015-10-03 14:45
Atom 1.0.7

I'll keep a look out for this issue.

**Comment by izuzak** [comment] 2015-10-03 19:10
Thanks, @radicaled. After looking into this a bit more, I think this is a duplicate of https://github.com/atom/bracket-matcher/issues/102 and was fixed by https://github.com/atom/atom/pull/8531 which was a part of Atom 1.0.8. In other words, you should no longer see this issue if you upgrade to the latest version of Atom (1.0.19), since you were on an old version which still had this problem. If you do notice it in 1.0.19 or later version when it's released -- please let me know. I'm going to close this now. :v:

**Closed by izuzak** 2015-10-03 19:10 UTC
Labels: uncaught-exception
